version: '2'

services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    image: agaveplatform/rstudio:3.4.3
    environment:
      - "ROOT=TRUE"
      - "USER=${AGAVE_USERNAME}"
      - "PASSWORD=${AGAVE_PASSWORD}"
      - "AGAVE_USERNAME=${AGAVE_USERNAME}"
      - "AGAVE_PASSWORD=${AGAVE_PASSWORD}"
      - "AGAVE_TENANT=${AGAVE_TENANT}"
      - "AGAVE_CACHE_DIR=/home/${AGAVE_USERNAME}/work/.agave"
      - "AGAVE_BASE_URL=${AGAVE_TENANT_BASEURL}"
      - "AGAVE_TENANT_BASE_URL=${AGAVE_TENANT_BASEURL}"
    ports:
      - "8787:8787"
    volumes:
      - .:/usr/lib/agave/rAgave
