# Agave Platform Science API
#
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
#
# Agave Platform version: 2.2.14
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AbstractApplicationParameterValue Class
#'
#' 
#'
#' @field defaultValue The default value for this parameter. The type will be determined by the value.type field.
#' @field enumValues An array of enumerated object values.
#' @field enquote Whether the argument value should be surrounded by quotation marks before injection into the wrapper template at runtime
#' @field order The order in which this parameter should be printed when generating an execution command for forked execution. This will also be the order in which paramters are returned in the response json.
#' @field required Is this parameter required? If visible is false, this must be true.
#' @field type The type of this parameter value. (Acceptable values are: \&quot;string\&quot;, \&quot;number\&quot;, \&quot;enumeration\&quot;, \&quot;bool\&quot;, \&quot;flag\&quot;)
#' @field validator The regular expression used to validate this parameter value. For enumerations, separate values with |
#' @field visible Should this parameter be visible? If not, there must be a default and it will be required.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AbstractApplicationParameterValue <- R6::R6Class(
  'AbstractApplicationParameterValue',
  public = list(
    `defaultValue` = NULL,
    `enumValues` = NULL,
    `enquote` = NULL,
    `order` = NULL,
    `required` = NULL,
    `type` = NULL,
    `validator` = NULL,
    `visible` = NULL,
    initialize = function(`defaultValue`, `enumValues`, `enquote`, `order`, `required`, `type`, `validator`, `visible`){
      if (!missing(`defaultValue`)) {
        stopifnot(is.character(`defaultValue`), length(`defaultValue`) == 1)
        self$`defaultValue` <- `defaultValue`
      }
      if (!missing(`enumValues`)) {
        stopifnot(is.character(`enumValues`), length(`enumValues`) == 1)
        self$`enumValues` <- `enumValues`
      }
      if (!missing(`enquote`)) {
        self$`enquote` <- `enquote`
      }
      if (!missing(`order`)) {
        stopifnot(is.numeric(`order`), length(`order`) == 1)
        self$`order` <- `order`
      }
      if (!missing(`required`)) {
        self$`required` <- `required`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`validator`)) {
        stopifnot(is.character(`validator`), length(`validator`) == 1)
        self$`validator` <- `validator`
      }
      if (!missing(`visible`)) {
        self$`visible` <- `visible`
      }
    },
    asJSON = function() {
      self$toJSON()
    },
    toJSON = function() {
      AbstractApplicationParameterValueObject <- list()
      if (!is.null(self$`defaultValue`)) {
        AbstractApplicationParameterValueObject[['defaultValue']] <- self$`defaultValue`
      }
      else {
        AbstractApplicationParameterValueObject[['defaultValue']] <- NULL
      }
      if (!is.null(self$`enumValues`)) {
        AbstractApplicationParameterValueObject[['enumValues']] <- self$`enumValues`
      }
      else {
        AbstractApplicationParameterValueObject[['enumValues']] <- NULL
      }
      if (!is.null(self$`enquote`)) {
        AbstractApplicationParameterValueObject[['enquote']] <- self$`enquote`
      }
      else {
        AbstractApplicationParameterValueObject[['enquote']] <- NULL
      }
      if (!is.null(self$`order`)) {
        AbstractApplicationParameterValueObject[['order']] <- self$`order`
      }
      else {
        AbstractApplicationParameterValueObject[['order']] <- NULL
      }
      if (!is.null(self$`required`)) {
        AbstractApplicationParameterValueObject[['required']] <- self$`required`
      }
      else {
        AbstractApplicationParameterValueObject[['required']] <- NULL
      }
      if (!is.null(self$`type`)) {
        AbstractApplicationParameterValueObject[['type']] <- self$`type`
      }
      else {
        AbstractApplicationParameterValueObject[['type']] <- NULL
      }
      if (!is.null(self$`validator`)) {
        AbstractApplicationParameterValueObject[['validator']] <- self$`validator`
      }
      else {
        AbstractApplicationParameterValueObject[['validator']] <- NULL
      }
      if (!is.null(self$`visible`)) {
        AbstractApplicationParameterValueObject[['visible']] <- self$`visible`
      }
      else {
        AbstractApplicationParameterValueObject[['visible']] <- NULL
      }

      AbstractApplicationParameterValueObject
    },
    fromJSON = function(AbstractApplicationParameterValueObject) {
      if (is.character(AbstractApplicationParameterValueObject)) {
        AbstractApplicationParameterValueObject <- jsonlite::fromJSON(AbstractApplicationParameterValueJson)
      }

      if ("result" %in% names(AbstractApplicationParameterValueObject)) {
        AbstractApplicationParameterValueObject <- AbstractApplicationParameterValueObject$result
      }

      if (!is.null(AbstractApplicationParameterValueObject$`defaultValue`)) {
        self$`defaultValue` <- AbstractApplicationParameterValueObject$`defaultValue`
      }
      if (!is.null(AbstractApplicationParameterValueObject$`enumValues`)) {
        self$`enumValues` <- AbstractApplicationParameterValueObject$`enumValues`
      }
      if (!is.null(AbstractApplicationParameterValueObject$`enquote`)) {
        self$`enquote` <- AbstractApplicationParameterValueObject$`enquote`
      }
      if (!is.null(AbstractApplicationParameterValueObject$`order`)) {
        self$`order` <- AbstractApplicationParameterValueObject$`order`
      }
      if (!is.null(AbstractApplicationParameterValueObject$`required`)) {
        self$`required` <- AbstractApplicationParameterValueObject$`required`
      }
      if (!is.null(AbstractApplicationParameterValueObject$`type`)) {
        self$`type` <- AbstractApplicationParameterValueObject$`type`
      }
      if (!is.null(AbstractApplicationParameterValueObject$`validator`)) {
        self$`validator` <- AbstractApplicationParameterValueObject$`validator`
      }
      if (!is.null(AbstractApplicationParameterValueObject$`visible`)) {
        self$`visible` <- AbstractApplicationParameterValueObject$`visible`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "defaultValue": %s,
           "enumValues": %s,
           "enquote": %s,
           "order": %d,
           "required": %s,
           "type": %s,
           "validator": %s,
           "visible": %s
        }',
        ifelse( is.null(self$`defaultValue`),"null",paste0(c('"', self$`defaultValue`, '"'))),
        ifelse( is.null(self$`enumValues`),"null",paste0(c('"', self$`enumValues`, '"'))),
        ifelse( is.null(self$`enquote`),"null",paste0(c('"', self$`enquote`, '"'))),
        ifelse( is.null(self$`order`),"null",paste0(c('"', self$`order`, '"'))),
        ifelse( is.null(self$`required`),"null",paste0(c('"', self$`required`, '"'))),
        ifelse( is.null(self$`type`),"null",paste0(c('"', self$`type`, '"'))),
        ifelse( is.null(self$`validator`),"null",paste0(c('"', self$`validator`, '"'))),
        ifelse( is.null(self$`visible`),"null",paste0(c('"', self$`visible`, '"')))
      )
    },
    fromJSONString = function(AbstractApplicationParameterValueJson) {
      AbstractApplicationParameterValueObject <- jsonlite::fromJSON(AbstractApplicationParameterValueJson)
      self::fromJSON(AbstractApplicationParameterValueObject)

    }
  )
)
