# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ACL Class
#'
#' @field execute 
#' @field read 
#' @field write 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ACL <- R6::R6Class(
  'ACL',
  public = list(
    `execute` = NULL,
    `read` = NULL,
    `write` = NULL,
    initialize = function(`execute`, `read`, `write`){
      if (!missing(`execute`)) {
        self$`execute` <- `execute`
      }
      if (!missing(`read`)) {
        self$`read` <- `read`
      }
      if (!missing(`write`)) {
        self$`write` <- `write`
      }
    },
    toJSON = function() {
      ACLObject <- list()
      if (!is.null(self$`execute`)) {
        ACLObject[['execute']] <- self$`execute`
      }
      if (!is.null(self$`read`)) {
        ACLObject[['read']] <- self$`read`
      }
      if (!is.null(self$`write`)) {
        ACLObject[['write']] <- self$`write`
      }

      ACLObject
    },
    fromJSON = function(ACLObject) {
      if (!is.null(ACLObject$`execute`)) {
        self$`execute` <- ACLObject$`execute`
      }
      if (!is.null(ACLObject$`read`)) {
        self$`read` <- ACLObject$`read`
      }
      if (!is.null(ACLObject$`write`)) {
        self$`write` <- ACLObject$`write`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "execute": %s,
           "read": %s,
           "write": %s
        }',
        self$`execute`,
        self$`read`,
        self$`write`
      )
    },
    fromJSONString = function(ACLJson) {
      ACLObject <- jsonlite::fromJSON(ACLJson)
      self$`execute` <- ACLObject$`execute`
      self$`read` <- ACLObject$`read`
      self$`write` <- ACLObject$`write`
    }
  )
)
