# Agave Platform Science API
#
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
#
# Agave Platform version: 2.2.14
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ApplicationArgumentDataSemantics Class
#'
#' Describes the semantic definition of this inputs and the filetypes it represents. Multiple ontologies and values are supported.
#'
#' @field fileTypes The file types acceptable for this output.
#' @field maxCardinality The maximum number of times this output may appear.
#' @field minCardinality The minimum number of times this output may appear. -1 is unlimited
#' @field ontology 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApplicationArgumentDataSemantics <- R6::R6Class(
  'ApplicationArgumentDataSemantics',
  public = list(
    `fileTypes` = NULL,
    `maxCardinality` = NULL,
    `minCardinality` = NULL,
    `ontology` = NULL,
    initialize = function(`fileTypes`, `maxCardinality`, `minCardinality`, `ontology`){
      if (!missing(`fileTypes`)) {
        stopifnot(is.list(`fileTypes`), length(`fileTypes`) != 0)
        lapply(`fileTypes`, function(x) stopifnot(is.character(x)))
        self$`fileTypes` <- `fileTypes`
      }
      if (!missing(`maxCardinality`)) {
        stopifnot(is.numeric(`maxCardinality`), length(`maxCardinality`) == 1)
        self$`maxCardinality` <- `maxCardinality`
      }
      if (!missing(`minCardinality`)) {
        stopifnot(is.numeric(`minCardinality`), length(`minCardinality`) == 1)
        self$`minCardinality` <- `minCardinality`
      }
      if (!missing(`ontology`)) {
        stopifnot(is.list(`ontology`), length(`ontology`) != 0)
        lapply(`ontology`, function(x) stopifnot(is.character(x)))
        self$`ontology` <- `ontology`
      }
    },
    asJSON = function() {
      self$toJSON()
    },
    toJSON = function() {
      ApplicationArgumentDataSemanticsObject <- list()
      if (!is.null(self$`fileTypes`)) {
        ApplicationArgumentDataSemanticsObject[['fileTypes']] <- self$`fileTypes`
      }
      else {
        ApplicationArgumentDataSemanticsObject[['fileTypes']] <- NULL
      }
      if (!is.null(self$`maxCardinality`)) {
        ApplicationArgumentDataSemanticsObject[['maxCardinality']] <- self$`maxCardinality`
      }
      else {
        ApplicationArgumentDataSemanticsObject[['maxCardinality']] <- NULL
      }
      if (!is.null(self$`minCardinality`)) {
        ApplicationArgumentDataSemanticsObject[['minCardinality']] <- self$`minCardinality`
      }
      else {
        ApplicationArgumentDataSemanticsObject[['minCardinality']] <- NULL
      }
      if (!is.null(self$`ontology`)) {
        ApplicationArgumentDataSemanticsObject[['ontology']] <- self$`ontology`
      }
      else {
        ApplicationArgumentDataSemanticsObject[['ontology']] <- NULL
      }

      ApplicationArgumentDataSemanticsObject
    },
    fromJSON = function(ApplicationArgumentDataSemanticsObject) {
      if (is.character(ApplicationArgumentDataSemanticsObject)) {
        ApplicationArgumentDataSemanticsObject <- jsonlite::fromJSON(ApplicationArgumentDataSemanticsJson)
      }

      if ("result" %in% names(ApplicationArgumentDataSemanticsObject)) {
        ApplicationArgumentDataSemanticsObject <- ApplicationArgumentDataSemanticsObject$result
      }

      if (!is.null(ApplicationArgumentDataSemanticsObject$`fileTypes`)) {
        self$`fileTypes` <- ApplicationArgumentDataSemanticsObject$`fileTypes`
      }
      if (!is.null(ApplicationArgumentDataSemanticsObject$`maxCardinality`)) {
        self$`maxCardinality` <- ApplicationArgumentDataSemanticsObject$`maxCardinality`
      }
      if (!is.null(ApplicationArgumentDataSemanticsObject$`minCardinality`)) {
        self$`minCardinality` <- ApplicationArgumentDataSemanticsObject$`minCardinality`
      }
      if (!is.null(ApplicationArgumentDataSemanticsObject$`ontology`)) {
        self$`ontology` <- ApplicationArgumentDataSemanticsObject$`ontology`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "fileTypes": [%s],
           "maxCardinality": %d,
           "minCardinality": %d,
           "ontology": [%s]
        }',
        lapply(self$`fileTypes`, function(x) paste(paste0('"', x, '"'), sep=",")),
        ifelse( is.null(self$`maxCardinality`),"null",paste0(c('"', self$`maxCardinality`, '"'))),
        ifelse( is.null(self$`minCardinality`),"null",paste0(c('"', self$`minCardinality`, '"'))),
        lapply(self$`ontology`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(ApplicationArgumentDataSemanticsJson) {
      ApplicationArgumentDataSemanticsObject <- jsonlite::fromJSON(ApplicationArgumentDataSemanticsJson)
      self::fromJSON(ApplicationArgumentDataSemanticsObject)

    }
  )
)
