# Agave Platform Science API
#
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
#
# Agave Platform version: 2.2.14
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ApplicationDisableAction Class
#'
#' Disables an app from use.
#'
#' @field action 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApplicationDisableAction <- R6::R6Class(
  'ApplicationDisableAction',
  public = list(
    `action` = NULL,
    initialize = function(`action`){
      if (!missing(`action`)) {
        stopifnot(R6::is.R6(`action`))
        self$`action` <- `action`
      }
    },
    asJSON = function() {
      self$toJSON()
    },
    toJSON = function() {
      ApplicationDisableActionObject <- list()
      if (!is.null(self$`action`)) {
        ApplicationDisableActionObject[['action']] <- self$`action`$toJSON()
      }
      else {
        ApplicationDisableActionObject[['action']] <- NULL
      }

      ApplicationDisableActionObject
    },
    fromJSON = function(ApplicationDisableActionObject) {
      if (is.character(ApplicationDisableActionObject)) {
        ApplicationDisableActionObject <- jsonlite::fromJSON(ApplicationDisableActionJson)
      }

      if ("result" %in% names(ApplicationDisableActionObject)) {
        ApplicationDisableActionObject <- ApplicationDisableActionObject$result
      }

      if (!is.null(ApplicationDisableActionObject$`action`)) {
        actionObject <- ApplicationActionType$new()
        actionObject$fromJSON(jsonlite::toJSON(ApplicationDisableActionObject$action, auto_unbox = TRUE))
        self$`action` <- actionObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "action": %s
        }',
        self$`action`$toJSON()
      )
    },
    fromJSONString = function(ApplicationDisableActionJson) {
      ApplicationDisableActionObject <- jsonlite::fromJSON(ApplicationDisableActionJson)
      self::fromJSON(ApplicationDisableActionObject)

    }
  )
)
