# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ApplicationOutput Class
#'
#' @field details 
#' @field id 
#' @field semantics 
#' @field value 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApplicationOutput <- R6::R6Class(
  'ApplicationOutput',
  public = list(
    `details` = NULL,
    `id` = NULL,
    `semantics` = NULL,
    `value` = NULL,
    initialize = function(`details`, `id`, `semantics`, `value`){
      if (!missing(`details`)) {
        stopifnot(R6::is.R6(`details`))
        self$`details` <- `details`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`semantics`)) {
        stopifnot(R6::is.R6(`semantics`))
        self$`semantics` <- `semantics`
      }
      if (!missing(`value`)) {
        stopifnot(R6::is.R6(`value`))
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      ApplicationOutputObject <- list()
      if (!is.null(self$`details`)) {
        ApplicationOutputObject[['details']] <- self$`details`$toJSON()
      }
      if (!is.null(self$`id`)) {
        ApplicationOutputObject[['id']] <- self$`id`
      }
      if (!is.null(self$`semantics`)) {
        ApplicationOutputObject[['semantics']] <- self$`semantics`$toJSON()
      }
      if (!is.null(self$`value`)) {
        ApplicationOutputObject[['value']] <- self$`value`$toJSON()
      }

      ApplicationOutputObject
    },
    fromJSON = function(ApplicationOutputObject) {
      if (!is.null(ApplicationOutputObject$`details`)) {
        detailsObject <- ApplicationArgumentDetails$new()
        detailsObject$fromJSON(jsonlite::toJSON(ApplicationOutputObject$details, auto_unbox = TRUE))
        self$`details` <- detailsObject
      }
      if (!is.null(ApplicationOutputObject$`id`)) {
        self$`id` <- ApplicationOutputObject$`id`
      }
      if (!is.null(ApplicationOutputObject$`semantics`)) {
        semanticsObject <- ApplicationArgumentSemantics$new()
        semanticsObject$fromJSON(jsonlite::toJSON(ApplicationOutputObject$semantics, auto_unbox = TRUE))
        self$`semantics` <- semanticsObject
      }
      if (!is.null(ApplicationOutputObject$`value`)) {
        valueObject <- ApplicationArgumentValue$new()
        valueObject$fromJSON(jsonlite::toJSON(ApplicationOutputObject$value, auto_unbox = TRUE))
        self$`value` <- valueObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "details": %s,
           "id": %s,
           "semantics": %s,
           "value": %s
        }',
        self$`details`$toJSON(),
        self$`id`,
        self$`semantics`$toJSON(),
        self$`value`$toJSON()
      )
    },
    fromJSONString = function(ApplicationOutputJson) {
      ApplicationOutputObject <- jsonlite::fromJSON(ApplicationOutputJson)
      ApplicationArgumentDetailsObject <- ApplicationArgumentDetails$new()
      self$`details` <- ApplicationArgumentDetailsObject$fromJSON(jsonlite::toJSON(ApplicationOutputObject$details, auto_unbox = TRUE))
      self$`id` <- ApplicationOutputObject$`id`
      ApplicationArgumentSemanticsObject <- ApplicationArgumentSemantics$new()
      self$`semantics` <- ApplicationArgumentSemanticsObject$fromJSON(jsonlite::toJSON(ApplicationOutputObject$semantics, auto_unbox = TRUE))
      ApplicationArgumentValueObject <- ApplicationArgumentValue$new()
      self$`value` <- ApplicationArgumentValueObject$fromJSON(jsonlite::toJSON(ApplicationOutputObject$value, auto_unbox = TRUE))
    }
  )
)
