# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ApplicationEnableAction Class
#'
#' @field action 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApplicationEnableAction <- R6::R6Class(
  'ApplicationEnableAction',
  public = list(
    `action` = NULL,
    initialize = function(`action`){
      if (!missing(`action`)) {
        stopifnot(R6::is.R6(`action`))
        self$`action` <- `action`
      }
    },
    toJSON = function() {
      ApplicationEnableActionObject <- list()
      if (!is.null(self$`action`)) {
        ApplicationEnableActionObject[['action']] <- self$`action`$toJSON()
      }

      ApplicationEnableActionObject
    },
    fromJSON = function(ApplicationEnableActionJson) {
      ApplicationEnableActionObject <- jsonlite::fromJSON(ApplicationEnableActionJson)
      if (!is.null(ApplicationEnableActionObject$`action`)) {
        actionObject <- ApplicationActionType$new()
        actionObject$fromJSON(jsonlite::toJSON(ApplicationEnableActionObject$action, auto_unbox = TRUE))
        self$`action` <- actionObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "action": %s
        }',
        self$`action`$toJSON()
      )
    },
    fromJSONString = function(ApplicationEnableActionJson) {
      ApplicationEnableActionObject <- jsonlite::fromJSON(ApplicationEnableActionJson)
      ApplicationActionTypeObject -> ApplicationActionType$new()
      self$`action` <- ApplicationActionTypeObject$fromJSON(jsonlite::toJSON(ApplicationEnableActionObject$action, auto_unbox = TRUE))
    }
  )
)
