# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Application Class
#'
#' @field available 
#' @field checkpointable 
#' @field defaultMaxRunTime 
#' @field defaultMemoryPerNode 
#' @field defaultNodeCount 
#' @field defaultProcessorsPerNode 
#' @field defaultQueue 
#' @field deploymentPath 
#' @field deploymentSystem 
#' @field executionSystem 
#' @field executionType 
#' @field helpURI 
#' @field id 
#' @field icon 
#' @field inputs 
#' @field label 
#' @field lastModified 
#' @field longDescription 
#' @field modules 
#' @field name 
#' @field ontology 
#' @field outputs 
#' @field parallelism 
#' @field parameters 
#' @field isPublic 
#' @field revision 
#' @field shortDescription 
#' @field tags 
#' @field templatePath 
#' @field testPath 
#' @field uuid 
#' @field version 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Application <- R6::R6Class(
  'Application',
  public = list(
    `available` = NULL,
    `checkpointable` = NULL,
    `defaultMaxRunTime` = NULL,
    `defaultMemoryPerNode` = NULL,
    `defaultNodeCount` = NULL,
    `defaultProcessorsPerNode` = NULL,
    `defaultQueue` = NULL,
    `deploymentPath` = NULL,
    `deploymentSystem` = NULL,
    `executionSystem` = NULL,
    `executionType` = NULL,
    `helpURI` = NULL,
    `id` = NULL,
    `icon` = NULL,
    `inputs` = NULL,
    `label` = NULL,
    `lastModified` = NULL,
    `longDescription` = NULL,
    `modules` = NULL,
    `name` = NULL,
    `ontology` = NULL,
    `outputs` = NULL,
    `parallelism` = NULL,
    `parameters` = NULL,
    `isPublic` = NULL,
    `revision` = NULL,
    `shortDescription` = NULL,
    `tags` = NULL,
    `templatePath` = NULL,
    `testPath` = NULL,
    `uuid` = NULL,
    `version` = NULL,
    initialize = function(`available`, `checkpointable`, `defaultMaxRunTime`, `defaultMemoryPerNode`, `defaultNodeCount`, `defaultProcessorsPerNode`, `defaultQueue`, `deploymentPath`, `deploymentSystem`, `executionSystem`, `executionType`, `helpURI`, `id`, `icon`, `inputs`, `label`, `lastModified`, `longDescription`, `modules`, `name`, `ontology`, `outputs`, `parallelism`, `parameters`, `isPublic`, `revision`, `shortDescription`, `tags`, `templatePath`, `testPath`, `uuid`, `version`){
      if (!missing(`available`)) {
        stopifnot(is.character(`available`), length(`available`) == 1)
        self$`available` <- `available`
      }
      if (!missing(`checkpointable`)) {
        stopifnot(is.character(`checkpointable`), length(`checkpointable`) == 1)
        self$`checkpointable` <- `checkpointable`
      }
      if (!missing(`defaultMaxRunTime`)) {
        stopifnot(is.character(`defaultMaxRunTime`), length(`defaultMaxRunTime`) == 1)
        self$`defaultMaxRunTime` <- `defaultMaxRunTime`
      }
      if (!missing(`defaultMemoryPerNode`)) {
        stopifnot(is.character(`defaultMemoryPerNode`), length(`defaultMemoryPerNode`) == 1)
        self$`defaultMemoryPerNode` <- `defaultMemoryPerNode`
      }
      if (!missing(`defaultNodeCount`)) {
        stopifnot(is.character(`defaultNodeCount`), length(`defaultNodeCount`) == 1)
        self$`defaultNodeCount` <- `defaultNodeCount`
      }
      if (!missing(`defaultProcessorsPerNode`)) {
        stopifnot(is.character(`defaultProcessorsPerNode`), length(`defaultProcessorsPerNode`) == 1)
        self$`defaultProcessorsPerNode` <- `defaultProcessorsPerNode`
      }
      if (!missing(`defaultQueue`)) {
        stopifnot(is.character(`defaultQueue`), length(`defaultQueue`) == 1)
        self$`defaultQueue` <- `defaultQueue`
      }
      if (!missing(`deploymentPath`)) {
        stopifnot(is.character(`deploymentPath`), length(`deploymentPath`) == 1)
        self$`deploymentPath` <- `deploymentPath`
      }
      if (!missing(`deploymentSystem`)) {
        stopifnot(is.character(`deploymentSystem`), length(`deploymentSystem`) == 1)
        self$`deploymentSystem` <- `deploymentSystem`
      }
      if (!missing(`executionSystem`)) {
        stopifnot(is.character(`executionSystem`), length(`executionSystem`) == 1)
        self$`executionSystem` <- `executionSystem`
      }
      if (!missing(`executionType`)) {
        stopifnot(is.character(`executionType`), length(`executionType`) == 1)
        self$`executionType` <- `executionType`
      }
      if (!missing(`helpURI`)) {
        stopifnot(is.character(`helpURI`), length(`helpURI`) == 1)
        self$`helpURI` <- `helpURI`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`icon`)) {
        stopifnot(is.character(`icon`), length(`icon`) == 1)
        self$`icon` <- `icon`
      }
      if (!missing(`inputs`)) {
        stopifnot(is.character(`inputs`), length(`inputs`) == 1)
        self$`inputs` <- `inputs`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`lastModified`)) {
        stopifnot(is.character(`lastModified`), length(`lastModified`) == 1)
        self$`lastModified` <- `lastModified`
      }
      if (!missing(`longDescription`)) {
        stopifnot(is.character(`longDescription`), length(`longDescription`) == 1)
        self$`longDescription` <- `longDescription`
      }
      if (!missing(`modules`)) {
        stopifnot(is.character(`modules`), length(`modules`) == 1)
        self$`modules` <- `modules`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`ontology`)) {
        stopifnot(is.character(`ontology`), length(`ontology`) == 1)
        self$`ontology` <- `ontology`
      }
      if (!missing(`outputs`)) {
        stopifnot(is.character(`outputs`), length(`outputs`) == 1)
        self$`outputs` <- `outputs`
      }
      if (!missing(`parallelism`)) {
        stopifnot(is.character(`parallelism`), length(`parallelism`) == 1)
        self$`parallelism` <- `parallelism`
      }
      if (!missing(`parameters`)) {
        stopifnot(is.character(`parameters`), length(`parameters`) == 1)
        self$`parameters` <- `parameters`
      }
      if (!missing(`isPublic`)) {
        stopifnot(is.character(`isPublic`), length(`isPublic`) == 1)
        self$`isPublic` <- `isPublic`
      }
      if (!missing(`revision`)) {
        stopifnot(is.character(`revision`), length(`revision`) == 1)
        self$`revision` <- `revision`
      }
      if (!missing(`shortDescription`)) {
        stopifnot(is.character(`shortDescription`), length(`shortDescription`) == 1)
        self$`shortDescription` <- `shortDescription`
      }
      if (!missing(`tags`)) {
        stopifnot(is.character(`tags`), length(`tags`) == 1)
        self$`tags` <- `tags`
      }
      if (!missing(`templatePath`)) {
        stopifnot(is.character(`templatePath`), length(`templatePath`) == 1)
        self$`templatePath` <- `templatePath`
      }
      if (!missing(`testPath`)) {
        stopifnot(is.character(`testPath`), length(`testPath`) == 1)
        self$`testPath` <- `testPath`
      }
      if (!missing(`uuid`)) {
        stopifnot(is.character(`uuid`), length(`uuid`) == 1)
        self$`uuid` <- `uuid`
      }
      if (!missing(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
    },
    toJSON = function() {
      ApplicationObject <- list()
      if (!is.null(self$`available`)) {
        ApplicationObject[['available']] <- self$`available`
      }
      if (!is.null(self$`checkpointable`)) {
        ApplicationObject[['checkpointable']] <- self$`checkpointable`
      }
      if (!is.null(self$`defaultMaxRunTime`)) {
        ApplicationObject[['defaultMaxRunTime']] <- self$`defaultMaxRunTime`
      }
      if (!is.null(self$`defaultMemoryPerNode`)) {
        ApplicationObject[['defaultMemoryPerNode']] <- self$`defaultMemoryPerNode`
      }
      if (!is.null(self$`defaultNodeCount`)) {
        ApplicationObject[['defaultNodeCount']] <- self$`defaultNodeCount`
      }
      if (!is.null(self$`defaultProcessorsPerNode`)) {
        ApplicationObject[['defaultProcessorsPerNode']] <- self$`defaultProcessorsPerNode`
      }
      if (!is.null(self$`defaultQueue`)) {
        ApplicationObject[['defaultQueue']] <- self$`defaultQueue`
      }
      if (!is.null(self$`deploymentPath`)) {
        ApplicationObject[['deploymentPath']] <- self$`deploymentPath`
      }
      if (!is.null(self$`deploymentSystem`)) {
        ApplicationObject[['deploymentSystem']] <- self$`deploymentSystem`
      }
      if (!is.null(self$`executionSystem`)) {
        ApplicationObject[['executionSystem']] <- self$`executionSystem`
      }
      if (!is.null(self$`executionType`)) {
        ApplicationObject[['executionType']] <- self$`executionType`
      }
      if (!is.null(self$`helpURI`)) {
        ApplicationObject[['helpURI']] <- self$`helpURI`
      }
      if (!is.null(self$`id`)) {
        ApplicationObject[['id']] <- self$`id`
      }
      if (!is.null(self$`icon`)) {
        ApplicationObject[['icon']] <- self$`icon`
      }
      if (!is.null(self$`inputs`)) {
        ApplicationObject[['inputs']] <- self$`inputs`
      }
      if (!is.null(self$`label`)) {
        ApplicationObject[['label']] <- self$`label`
      }
      if (!is.null(self$`lastModified`)) {
        ApplicationObject[['lastModified']] <- self$`lastModified`
      }
      if (!is.null(self$`longDescription`)) {
        ApplicationObject[['longDescription']] <- self$`longDescription`
      }
      if (!is.null(self$`modules`)) {
        ApplicationObject[['modules']] <- self$`modules`
      }
      if (!is.null(self$`name`)) {
        ApplicationObject[['name']] <- self$`name`
      }
      if (!is.null(self$`ontology`)) {
        ApplicationObject[['ontology']] <- self$`ontology`
      }
      if (!is.null(self$`outputs`)) {
        ApplicationObject[['outputs']] <- self$`outputs`
      }
      if (!is.null(self$`parallelism`)) {
        ApplicationObject[['parallelism']] <- self$`parallelism`
      }
      if (!is.null(self$`parameters`)) {
        ApplicationObject[['parameters']] <- self$`parameters`
      }
      if (!is.null(self$`isPublic`)) {
        ApplicationObject[['isPublic']] <- self$`isPublic`
      }
      if (!is.null(self$`revision`)) {
        ApplicationObject[['revision']] <- self$`revision`
      }
      if (!is.null(self$`shortDescription`)) {
        ApplicationObject[['shortDescription']] <- self$`shortDescription`
      }
      if (!is.null(self$`tags`)) {
        ApplicationObject[['tags']] <- self$`tags`
      }
      if (!is.null(self$`templatePath`)) {
        ApplicationObject[['templatePath']] <- self$`templatePath`
      }
      if (!is.null(self$`testPath`)) {
        ApplicationObject[['testPath']] <- self$`testPath`
      }
      if (!is.null(self$`uuid`)) {
        ApplicationObject[['uuid']] <- self$`uuid`
      }
      if (!is.null(self$`version`)) {
        ApplicationObject[['version']] <- self$`version`
      }

      ApplicationObject
    },
    fromJSON = function(ApplicationJson) {
      ApplicationObject <- jsonlite::fromJSON(ApplicationJson)
      if (!is.null(ApplicationObject$`available`)) {
        self$`available` <- ApplicationObject$`available`
      }
      if (!is.null(ApplicationObject$`checkpointable`)) {
        self$`checkpointable` <- ApplicationObject$`checkpointable`
      }
      if (!is.null(ApplicationObject$`defaultMaxRunTime`)) {
        self$`defaultMaxRunTime` <- ApplicationObject$`defaultMaxRunTime`
      }
      if (!is.null(ApplicationObject$`defaultMemoryPerNode`)) {
        self$`defaultMemoryPerNode` <- ApplicationObject$`defaultMemoryPerNode`
      }
      if (!is.null(ApplicationObject$`defaultNodeCount`)) {
        self$`defaultNodeCount` <- ApplicationObject$`defaultNodeCount`
      }
      if (!is.null(ApplicationObject$`defaultProcessorsPerNode`)) {
        self$`defaultProcessorsPerNode` <- ApplicationObject$`defaultProcessorsPerNode`
      }
      if (!is.null(ApplicationObject$`defaultQueue`)) {
        self$`defaultQueue` <- ApplicationObject$`defaultQueue`
      }
      if (!is.null(ApplicationObject$`deploymentPath`)) {
        self$`deploymentPath` <- ApplicationObject$`deploymentPath`
      }
      if (!is.null(ApplicationObject$`deploymentSystem`)) {
        self$`deploymentSystem` <- ApplicationObject$`deploymentSystem`
      }
      if (!is.null(ApplicationObject$`executionSystem`)) {
        self$`executionSystem` <- ApplicationObject$`executionSystem`
      }
      if (!is.null(ApplicationObject$`executionType`)) {
        self$`executionType` <- ApplicationObject$`executionType`
      }
      if (!is.null(ApplicationObject$`helpURI`)) {
        self$`helpURI` <- ApplicationObject$`helpURI`
      }
      if (!is.null(ApplicationObject$`id`)) {
        self$`id` <- ApplicationObject$`id`
      }
      if (!is.null(ApplicationObject$`icon`)) {
        self$`icon` <- ApplicationObject$`icon`
      }
      if (!is.null(ApplicationObject$`inputs`)) {
        self$`inputs` <- ApplicationObject$`inputs`
      }
      if (!is.null(ApplicationObject$`label`)) {
        self$`label` <- ApplicationObject$`label`
      }
      if (!is.null(ApplicationObject$`lastModified`)) {
        self$`lastModified` <- ApplicationObject$`lastModified`
      }
      if (!is.null(ApplicationObject$`longDescription`)) {
        self$`longDescription` <- ApplicationObject$`longDescription`
      }
      if (!is.null(ApplicationObject$`modules`)) {
        self$`modules` <- ApplicationObject$`modules`
      }
      if (!is.null(ApplicationObject$`name`)) {
        self$`name` <- ApplicationObject$`name`
      }
      if (!is.null(ApplicationObject$`ontology`)) {
        self$`ontology` <- ApplicationObject$`ontology`
      }
      if (!is.null(ApplicationObject$`outputs`)) {
        self$`outputs` <- ApplicationObject$`outputs`
      }
      if (!is.null(ApplicationObject$`parallelism`)) {
        self$`parallelism` <- ApplicationObject$`parallelism`
      }
      if (!is.null(ApplicationObject$`parameters`)) {
        self$`parameters` <- ApplicationObject$`parameters`
      }
      if (!is.null(ApplicationObject$`isPublic`)) {
        self$`isPublic` <- ApplicationObject$`isPublic`
      }
      if (!is.null(ApplicationObject$`revision`)) {
        self$`revision` <- ApplicationObject$`revision`
      }
      if (!is.null(ApplicationObject$`shortDescription`)) {
        self$`shortDescription` <- ApplicationObject$`shortDescription`
      }
      if (!is.null(ApplicationObject$`tags`)) {
        self$`tags` <- ApplicationObject$`tags`
      }
      if (!is.null(ApplicationObject$`templatePath`)) {
        self$`templatePath` <- ApplicationObject$`templatePath`
      }
      if (!is.null(ApplicationObject$`testPath`)) {
        self$`testPath` <- ApplicationObject$`testPath`
      }
      if (!is.null(ApplicationObject$`uuid`)) {
        self$`uuid` <- ApplicationObject$`uuid`
      }
      if (!is.null(ApplicationObject$`version`)) {
        self$`version` <- ApplicationObject$`version`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "available": %s,
           "checkpointable": %s,
           "defaultMaxRunTime": %s,
           "defaultMemoryPerNode": %s,
           "defaultNodeCount": %s,
           "defaultProcessorsPerNode": %s,
           "defaultQueue": %s,
           "deploymentPath": %s,
           "deploymentSystem": %s,
           "executionSystem": %s,
           "executionType": %s,
           "helpURI": %s,
           "id": %s,
           "icon": %s,
           "inputs": %s,
           "label": %s,
           "lastModified": %s,
           "longDescription": %s,
           "modules": %s,
           "name": %s,
           "ontology": %s,
           "outputs": %s,
           "parallelism": %s,
           "parameters": %s,
           "isPublic": %s,
           "revision": %s,
           "shortDescription": %s,
           "tags": %s,
           "templatePath": %s,
           "testPath": %s,
           "uuid": %s,
           "version": %s
        }',
        self$`available`,
        self$`checkpointable`,
        self$`defaultMaxRunTime`,
        self$`defaultMemoryPerNode`,
        self$`defaultNodeCount`,
        self$`defaultProcessorsPerNode`,
        self$`defaultQueue`,
        self$`deploymentPath`,
        self$`deploymentSystem`,
        self$`executionSystem`,
        self$`executionType`,
        self$`helpURI`,
        self$`id`,
        self$`icon`,
        self$`inputs`,
        self$`label`,
        self$`lastModified`,
        self$`longDescription`,
        self$`modules`,
        self$`name`,
        self$`ontology`,
        self$`outputs`,
        self$`parallelism`,
        self$`parameters`,
        self$`isPublic`,
        self$`revision`,
        self$`shortDescription`,
        self$`tags`,
        self$`templatePath`,
        self$`testPath`,
        self$`uuid`,
        self$`version`
      )
    },
    fromJSONString = function(ApplicationJson) {
      ApplicationObject <- jsonlite::fromJSON(ApplicationJson)
      self$`available` <- ApplicationObject$`available`
      self$`checkpointable` <- ApplicationObject$`checkpointable`
      self$`defaultMaxRunTime` <- ApplicationObject$`defaultMaxRunTime`
      self$`defaultMemoryPerNode` <- ApplicationObject$`defaultMemoryPerNode`
      self$`defaultNodeCount` <- ApplicationObject$`defaultNodeCount`
      self$`defaultProcessorsPerNode` <- ApplicationObject$`defaultProcessorsPerNode`
      self$`defaultQueue` <- ApplicationObject$`defaultQueue`
      self$`deploymentPath` <- ApplicationObject$`deploymentPath`
      self$`deploymentSystem` <- ApplicationObject$`deploymentSystem`
      self$`executionSystem` <- ApplicationObject$`executionSystem`
      self$`executionType` <- ApplicationObject$`executionType`
      self$`helpURI` <- ApplicationObject$`helpURI`
      self$`id` <- ApplicationObject$`id`
      self$`icon` <- ApplicationObject$`icon`
      self$`inputs` <- ApplicationObject$`inputs`
      self$`label` <- ApplicationObject$`label`
      self$`lastModified` <- ApplicationObject$`lastModified`
      self$`longDescription` <- ApplicationObject$`longDescription`
      self$`modules` <- ApplicationObject$`modules`
      self$`name` <- ApplicationObject$`name`
      self$`ontology` <- ApplicationObject$`ontology`
      self$`outputs` <- ApplicationObject$`outputs`
      self$`parallelism` <- ApplicationObject$`parallelism`
      self$`parameters` <- ApplicationObject$`parameters`
      self$`isPublic` <- ApplicationObject$`isPublic`
      self$`revision` <- ApplicationObject$`revision`
      self$`shortDescription` <- ApplicationObject$`shortDescription`
      self$`tags` <- ApplicationObject$`tags`
      self$`templatePath` <- ApplicationObject$`templatePath`
      self$`testPath` <- ApplicationObject$`testPath`
      self$`uuid` <- ApplicationObject$`uuid`
      self$`version` <- ApplicationObject$`version`
    }
  )
)
