# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ClientRequest Class
#'
#' @field name 
#' @field description 
#' @field tier 
#' @field callbackUrl 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ClientRequest <- R6::R6Class(
  'ClientRequest',
  public = list(
    `name` = NULL,
    `description` = NULL,
    `tier` = NULL,
    `callbackUrl` = NULL,
    initialize = function(`name`, `description`, `tier`, `callbackUrl`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`tier`)) {
        stopifnot(R6::is.R6(`tier`))
        self$`tier` <- `tier`
      }
      if (!missing(`callbackUrl`)) {
        stopifnot(is.character(`callbackUrl`), length(`callbackUrl`) == 1)
        self$`callbackUrl` <- `callbackUrl`
      }
    },
    toJSON = function() {
      ClientRequestObject <- list()
      if (!is.null(self$`name`)) {
        ClientRequestObject[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        ClientRequestObject[['description']] <- self$`description`
      }
      if (!is.null(self$`tier`)) {
        ClientRequestObject[['tier']] <- self$`tier`$toJSON()
      }
      if (!is.null(self$`callbackUrl`)) {
        ClientRequestObject[['callbackUrl']] <- self$`callbackUrl`
      }

      ClientRequestObject
    },
    fromJSON = function(ClientRequestObject) {
      if (!is.null(ClientRequestObject$`name`)) {
        self$`name` <- ClientRequestObject$`name`
      }
      if (!is.null(ClientRequestObject$`description`)) {
        self$`description` <- ClientRequestObject$`description`
      }
      if (!is.null(ClientRequestObject$`tier`)) {
        tierObject <- ClientSubscriptionTier$new()
        tierObject$fromJSON(jsonlite::toJSON(ClientRequestObject$tier, auto_unbox = TRUE))
        self$`tier` <- tierObject
      }
      if (!is.null(ClientRequestObject$`callbackUrl`)) {
        self$`callbackUrl` <- ClientRequestObject$`callbackUrl`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "description": %s,
           "tier": %s,
           "callbackUrl": %s
        }',
        self$`name`,
        self$`description`,
        self$`tier`$toJSON(),
        self$`callbackUrl`
      )
    },
    fromJSONString = function(ClientRequestJson) {
      ClientRequestObject <- jsonlite::fromJSON(ClientRequestJson)
      self$`name` <- ClientRequestObject$`name`
      self$`description` <- ClientRequestObject$`description`
      ClientSubscriptionTierObject <- ClientSubscriptionTier$new()
      self$`tier` <- ClientSubscriptionTierObject$fromJSON(jsonlite::toJSON(ClientRequestObject$tier, auto_unbox = TRUE))
      self$`callbackUrl` <- ClientRequestObject$`callbackUrl`
    }
  )
)
