# Agave Platform Science API
#
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
#
# Agave Platform version: 2.2.14
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' EmptyApplicationResponse Class
#'
#' 
#'
#' @field message success or failure
#' @field result empty result
#' @field status success or failure
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EmptyApplicationResponse <- R6::R6Class(
  'EmptyApplicationResponse',
  public = list(
    `message` = NULL,
    `result` = NULL,
    `status` = NULL,
    initialize = function(`message`, `result`, `status`){
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`result`)) {
        stopifnot(is.character(`result`), length(`result`) == 1)
        self$`result` <- `result`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
    },
    asJSON = function() {
      self$toJSON()
    },
    toJSON = function() {
      EmptyApplicationResponseObject <- list()
      if (!is.null(self$`message`)) {
        EmptyApplicationResponseObject[['message']] <- self$`message`
      }
      else {
        EmptyApplicationResponseObject[['message']] <- NULL
      }
      if (!is.null(self$`result`)) {
        EmptyApplicationResponseObject[['result']] <- self$`result`
      }
      else {
        EmptyApplicationResponseObject[['result']] <- NULL
      }
      if (!is.null(self$`status`)) {
        EmptyApplicationResponseObject[['status']] <- self$`status`
      }
      else {
        EmptyApplicationResponseObject[['status']] <- NULL
      }

      EmptyApplicationResponseObject
    },
    fromJSON = function(EmptyApplicationResponseObject) {
      if (is.character(EmptyApplicationResponseObject)) {
        EmptyApplicationResponseObject <- jsonlite::fromJSON(EmptyApplicationResponseJson)
      }

      if ("result" %in% names(EmptyApplicationResponseObject)) {
        EmptyApplicationResponseObject <- EmptyApplicationResponseObject$result
      }

      if (!is.null(EmptyApplicationResponseObject$`message`)) {
        self$`message` <- EmptyApplicationResponseObject$`message`
      }
      if (!is.null(EmptyApplicationResponseObject$`result`)) {
        self$`result` <- EmptyApplicationResponseObject$`result`
      }
      if (!is.null(EmptyApplicationResponseObject$`status`)) {
        self$`status` <- EmptyApplicationResponseObject$`status`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "message": %s,
           "result": %s,
           "status": %s
        }',
        ifelse( is.null(self$`message`),"null",paste0(c('"', self$`message`, '"'))),
        ifelse( is.null(self$`result`),"null",paste0(c('"', self$`result`, '"'))),
        ifelse( is.null(self$`status`),"null",paste0(c('"', self$`status`, '"')))
      )
    },
    fromJSONString = function(EmptyApplicationResponseJson) {
      EmptyApplicationResponseObject <- jsonlite::fromJSON(EmptyApplicationResponseJson)
      self::fromJSON(EmptyApplicationResponseObject)

    }
  )
)
