# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ExecutionSystem Class
#'
#' @field description 
#' @field environment 
#' @field id 
#' @field isDefault 
#' @field isPublic 
#' @field lastModified 
#' @field name 
#' @field revision 
#' @field scratchDir 
#' @field site 
#' @field status 
#' @field storage 
#' @field type 
#' @field uuid 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ExecutionSystem <- R6::R6Class(
  'ExecutionSystem',
  public = list(
    `description` = NULL,
    `environment` = NULL,
    `id` = NULL,
    `isDefault` = NULL,
    `isPublic` = NULL,
    `lastModified` = NULL,
    `name` = NULL,
    `revision` = NULL,
    `scratchDir` = NULL,
    `site` = NULL,
    `status` = NULL,
    `storage` = NULL,
    `type` = NULL,
    `uuid` = NULL,
    initialize = function(`description`, `environment`, `id`, `isDefault`, `isPublic`, `lastModified`, `name`, `revision`, `scratchDir`, `site`, `status`, `storage`, `type`, `uuid`){
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`environment`)) {
        stopifnot(is.character(`environment`), length(`environment`) == 1)
        self$`environment` <- `environment`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`isDefault`)) {
        self$`isDefault` <- `isDefault`
      }
      if (!missing(`isPublic`)) {
        self$`isPublic` <- `isPublic`
      }
      if (!missing(`lastModified`)) {
        stopifnot(is.character(`lastModified`), length(`lastModified`) == 1)
        self$`lastModified` <- `lastModified`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`revision`)) {
        stopifnot(is.numeric(`revision`), length(`revision`) == 1)
        self$`revision` <- `revision`
      }
      if (!missing(`scratchDir`)) {
        stopifnot(is.character(`scratchDir`), length(`scratchDir`) == 1)
        self$`scratchDir` <- `scratchDir`
      }
      if (!missing(`site`)) {
        stopifnot(is.character(`site`), length(`site`) == 1)
        self$`site` <- `site`
      }
      if (!missing(`status`)) {
        stopifnot(R6::is.R6(`status`))
        self$`status` <- `status`
      }
      if (!missing(`storage`)) {
        stopifnot(R6::is.R6(`storage`))
        self$`storage` <- `storage`
      }
      if (!missing(`type`)) {
        stopifnot(R6::is.R6(`type`))
        self$`type` <- `type`
      }
      if (!missing(`uuid`)) {
        stopifnot(is.character(`uuid`), length(`uuid`) == 1)
        self$`uuid` <- `uuid`
      }
    },
    toJSON = function() {
      ExecutionSystemObject <- list()
      if (!is.null(self$`description`)) {
        ExecutionSystemObject[['description']] <- self$`description`
      }
      if (!is.null(self$`environment`)) {
        ExecutionSystemObject[['environment']] <- self$`environment`
      }
      if (!is.null(self$`id`)) {
        ExecutionSystemObject[['id']] <- self$`id`
      }
      if (!is.null(self$`isDefault`)) {
        ExecutionSystemObject[['isDefault']] <- self$`isDefault`
      }
      if (!is.null(self$`isPublic`)) {
        ExecutionSystemObject[['isPublic']] <- self$`isPublic`
      }
      if (!is.null(self$`lastModified`)) {
        ExecutionSystemObject[['lastModified']] <- self$`lastModified`
      }
      if (!is.null(self$`name`)) {
        ExecutionSystemObject[['name']] <- self$`name`
      }
      if (!is.null(self$`revision`)) {
        ExecutionSystemObject[['revision']] <- self$`revision`
      }
      if (!is.null(self$`scratchDir`)) {
        ExecutionSystemObject[['scratchDir']] <- self$`scratchDir`
      }
      if (!is.null(self$`site`)) {
        ExecutionSystemObject[['site']] <- self$`site`
      }
      if (!is.null(self$`status`)) {
        ExecutionSystemObject[['status']] <- self$`status`$toJSON()
      }
      if (!is.null(self$`storage`)) {
        ExecutionSystemObject[['storage']] <- self$`storage`$toJSON()
      }
      if (!is.null(self$`type`)) {
        ExecutionSystemObject[['type']] <- self$`type`$toJSON()
      }
      if (!is.null(self$`uuid`)) {
        ExecutionSystemObject[['uuid']] <- self$`uuid`
      }

      ExecutionSystemObject
    },
    fromJSON = function(ExecutionSystemJson) {
      ExecutionSystemObject <- jsonlite::fromJSON(ExecutionSystemJson)
      if (!is.null(ExecutionSystemObject$`description`)) {
        self$`description` <- ExecutionSystemObject$`description`
      }
      if (!is.null(ExecutionSystemObject$`environment`)) {
        self$`environment` <- ExecutionSystemObject$`environment`
      }
      if (!is.null(ExecutionSystemObject$`id`)) {
        self$`id` <- ExecutionSystemObject$`id`
      }
      if (!is.null(ExecutionSystemObject$`isDefault`)) {
        self$`isDefault` <- ExecutionSystemObject$`isDefault`
      }
      if (!is.null(ExecutionSystemObject$`isPublic`)) {
        self$`isPublic` <- ExecutionSystemObject$`isPublic`
      }
      if (!is.null(ExecutionSystemObject$`lastModified`)) {
        self$`lastModified` <- ExecutionSystemObject$`lastModified`
      }
      if (!is.null(ExecutionSystemObject$`name`)) {
        self$`name` <- ExecutionSystemObject$`name`
      }
      if (!is.null(ExecutionSystemObject$`revision`)) {
        self$`revision` <- ExecutionSystemObject$`revision`
      }
      if (!is.null(ExecutionSystemObject$`scratchDir`)) {
        self$`scratchDir` <- ExecutionSystemObject$`scratchDir`
      }
      if (!is.null(ExecutionSystemObject$`site`)) {
        self$`site` <- ExecutionSystemObject$`site`
      }
      if (!is.null(ExecutionSystemObject$`status`)) {
        statusObject <- SystemStatusType$new()
        statusObject$fromJSON(jsonlite::toJSON(ExecutionSystemObject$status, auto_unbox = TRUE))
        self$`status` <- statusObject
      }
      if (!is.null(ExecutionSystemObject$`storage`)) {
        storageObject <- SystemStorageConfig$new()
        storageObject$fromJSON(jsonlite::toJSON(ExecutionSystemObject$storage, auto_unbox = TRUE))
        self$`storage` <- storageObject
      }
      if (!is.null(ExecutionSystemObject$`type`)) {
        typeObject <- SystemType$new()
        typeObject$fromJSON(jsonlite::toJSON(ExecutionSystemObject$type, auto_unbox = TRUE))
        self$`type` <- typeObject
      }
      if (!is.null(ExecutionSystemObject$`uuid`)) {
        self$`uuid` <- ExecutionSystemObject$`uuid`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "description": %s,
           "environment": %s,
           "id": %s,
           "isDefault": %s,
           "isPublic": %s,
           "lastModified": %s,
           "name": %s,
           "revision": %d,
           "scratchDir": %s,
           "site": %s,
           "status": %s,
           "storage": %s,
           "type": %s,
           "uuid": %s
        }',
        self$`description`,
        self$`environment`,
        self$`id`,
        self$`isDefault`,
        self$`isPublic`,
        self$`lastModified`,
        self$`name`,
        self$`revision`,
        self$`scratchDir`,
        self$`site`,
        self$`status`$toJSON(),
        self$`storage`$toJSON(),
        self$`type`$toJSON(),
        self$`uuid`
      )
    },
    fromJSONString = function(ExecutionSystemJson) {
      ExecutionSystemObject <- jsonlite::fromJSON(ExecutionSystemJson)
      self$`description` <- ExecutionSystemObject$`description`
      self$`environment` <- ExecutionSystemObject$`environment`
      self$`id` <- ExecutionSystemObject$`id`
      self$`isDefault` <- ExecutionSystemObject$`isDefault`
      self$`isPublic` <- ExecutionSystemObject$`isPublic`
      self$`lastModified` <- ExecutionSystemObject$`lastModified`
      self$`name` <- ExecutionSystemObject$`name`
      self$`revision` <- ExecutionSystemObject$`revision`
      self$`scratchDir` <- ExecutionSystemObject$`scratchDir`
      self$`site` <- ExecutionSystemObject$`site`
      SystemStatusTypeObject -> SystemStatusType$new()
      self$`status` <- SystemStatusTypeObject$fromJSON(jsonlite::toJSON(ExecutionSystemObject$status, auto_unbox = TRUE))
      SystemStorageConfigObject -> SystemStorageConfig$new()
      self$`storage` <- SystemStorageConfigObject$fromJSON(jsonlite::toJSON(ExecutionSystemObject$storage, auto_unbox = TRUE))
      SystemTypeObject -> SystemType$new()
      self$`type` <- SystemTypeObject$fromJSON(jsonlite::toJSON(ExecutionSystemObject$type, auto_unbox = TRUE))
      self$`uuid` <- ExecutionSystemObject$`uuid`
    }
  )
)
