# Agave Platform Science API
#
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
#
# Agave Platform version: 2.2.14
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' FileCopyAction Class
#'
#' Request for a file/folder to be copied on the target system. Metadata will be appended to the destination if it already exists. Otherwise, a new history will be created.
#'
#' @field action 
#' @field path Name of new directory or target file or folder.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FileCopyAction <- R6::R6Class(
  'FileCopyAction',
  public = list(
    `action` = NULL,
    `path` = NULL,
    initialize = function(`action`, `path`){
      if (!missing(`action`)) {
        stopifnot(R6::is.R6(`action`))
        self$`action` <- `action`
      }
      if (!missing(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
    },
    asJSON = function() {
      self$toJSON()
    },
    toJSON = function() {
      FileCopyActionObject <- list()
      if (!is.null(self$`action`)) {
        FileCopyActionObject[['action']] <- self$`action`$toJSON()
      }
      else {
        FileCopyActionObject[['action']] <- NULL
      }
      if (!is.null(self$`path`)) {
        FileCopyActionObject[['path']] <- self$`path`
      }
      else {
        FileCopyActionObject[['path']] <- NULL
      }

      FileCopyActionObject
    },
    fromJSON = function(FileCopyActionObject) {
      if (is.character(FileCopyActionObject)) {
        FileCopyActionObject <- jsonlite::fromJSON(FileCopyActionJson)
      }

      if ("result" %in% names(FileCopyActionObject)) {
        FileCopyActionObject <- FileCopyActionObject$result
      }

      if (!is.null(FileCopyActionObject$`action`)) {
        actionObject <- FileManagementActionType$new()
        actionObject$fromJSON(jsonlite::toJSON(FileCopyActionObject$action, auto_unbox = TRUE))
        self$`action` <- actionObject
      }
      if (!is.null(FileCopyActionObject$`path`)) {
        self$`path` <- FileCopyActionObject$`path`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "action": %s,
           "path": %s
        }',
        self$`action`$toJSON(),
        ifelse( is.null(self$`path`),"null",paste0(c('"', self$`path`, '"')))
      )
    },
    fromJSONString = function(FileCopyActionJson) {
      FileCopyActionObject <- jsonlite::fromJSON(FileCopyActionJson)
      self::fromJSON(FileCopyActionObject)

    }
  )
)
