# Agave Platform Science API
#
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
#
# Agave Platform version: 2.2.14
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' FileType Class
#'
#' The type of the remote file/folder
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FileType <- R6::R6Class(
  'FileType',
  public = list(
    initialize = function(){
    },
    asJSON = function() {
      self$toJSON()
    },
    toJSON = function() {
      FileTypeObject <- list()

      FileTypeObject
    },
    fromJSON = function(FileTypeObject) {
      if (is.character(FileTypeObject)) {
        FileTypeObject <- jsonlite::fromJSON(FileTypeJson)
      }

      if ("result" %in% names(FileTypeObject)) {
        FileTypeObject <- FileTypeObject$result
      }

    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(FileTypeJson) {
      FileTypeObject <- jsonlite::fromJSON(FileTypeJson)
      self::fromJSON(FileTypeObject)

    }
  )
)
