# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' FileMoveAction Class
#'
#' @field action 
#' @field path 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FileMoveAction <- R6::R6Class(
  'FileMoveAction',
  public = list(
    `action` = NULL,
    `path` = NULL,
    initialize = function(`action`, `path`){
      if (!missing(`action`)) {
        stopifnot(R6::is.R6(`action`))
        self$`action` <- `action`
      }
      if (!missing(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
    },
    toJSON = function() {
      FileMoveActionObject <- list()
      if (!is.null(self$`action`)) {
        FileMoveActionObject[['action']] <- self$`action`$toJSON()
      }
      if (!is.null(self$`path`)) {
        FileMoveActionObject[['path']] <- self$`path`
      }

      FileMoveActionObject
    },
    fromJSON = function(FileMoveActionObject) {
      if (!is.null(FileMoveActionObject$`action`)) {
        actionObject <- FileManagementActionType$new()
        actionObject$fromJSON(jsonlite::toJSON(FileMoveActionObject$action, auto_unbox = TRUE))
        self$`action` <- actionObject
      }
      if (!is.null(FileMoveActionObject$`path`)) {
        self$`path` <- FileMoveActionObject$`path`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "action": %s,
           "path": %s
        }',
        self$`action`$toJSON(),
        self$`path`
      )
    },
    fromJSONString = function(FileMoveActionJson) {
      FileMoveActionObject <- jsonlite::fromJSON(FileMoveActionJson)
      FileManagementActionTypeObject <- FileManagementActionType$new()
      self$`action` <- FileManagementActionTypeObject$fromJSON(jsonlite::toJSON(FileMoveActionObject$action, auto_unbox = TRUE))
      self$`path` <- FileMoveActionObject$`path`
    }
  )
)
