# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' FilePermissionStanza Class
#'
#' @field read 
#' @field write 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FilePermissionStanza <- R6::R6Class(
  'FilePermissionStanza',
  public = list(
    `read` = NULL,
    `write` = NULL,
    initialize = function(`read`, `write`){
      if (!missing(`read`)) {
        self$`read` <- `read`
      }
      if (!missing(`write`)) {
        self$`write` <- `write`
      }
    },
    toJSON = function() {
      FilePermissionStanzaObject <- list()
      if (!is.null(self$`read`)) {
        FilePermissionStanzaObject[['read']] <- self$`read`
      }
      if (!is.null(self$`write`)) {
        FilePermissionStanzaObject[['write']] <- self$`write`
      }

      FilePermissionStanzaObject
    },
    fromJSON = function(FilePermissionStanzaJson) {
      FilePermissionStanzaObject <- jsonlite::fromJSON(FilePermissionStanzaJson)
      if (!is.null(FilePermissionStanzaObject$`read`)) {
        self$`read` <- FilePermissionStanzaObject$`read`
      }
      if (!is.null(FilePermissionStanzaObject$`write`)) {
        self$`write` <- FilePermissionStanzaObject$`write`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "read": %s,
           "write": %s
        }',
        self$`read`,
        self$`write`
      )
    },
    fromJSONString = function(FilePermissionStanzaJson) {
      FilePermissionStanzaObject <- jsonlite::fromJSON(FilePermissionStanzaJson)
      self$`read` <- FilePermissionStanzaObject$`read`
      self$`write` <- FilePermissionStanzaObject$`write`
    }
  )
)
