# Agave Platform Science API
#
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
#
# Agave Platform version: 2.2.14
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Gender Class
#'
#' The gender of the user
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Gender <- R6::R6Class(
  'Gender',
  public = list(
    initialize = function(){
    },
    asJSON = function() {
      self$toJSON()
    },
    toJSON = function() {
      GenderObject <- list()

      GenderObject
    },
    fromJSON = function(GenderObject) {
      if (is.character(GenderObject)) {
        GenderObject <- jsonlite::fromJSON(GenderJson)
      }

      if ("result" %in% names(GenderObject)) {
        GenderObject <- GenderObject$result
      }

    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(GenderJson) {
      GenderObject <- jsonlite::fromJSON(GenderJson)
      self::fromJSON(GenderObject)

    }
  )
)
