# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' HistoryEvent Class
#'
#' @field created 
#' @field description 
#' @field status 
#' @field progress 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HistoryEvent <- R6::R6Class(
  'HistoryEvent',
  public = list(
    `created` = NULL,
    `description` = NULL,
    `status` = NULL,
    `progress` = NULL,
    initialize = function(`created`, `description`, `status`, `progress`){
      if (!missing(`created`)) {
        stopifnot(is.character(`created`), length(`created`) == 1)
        self$`created` <- `created`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`progress`)) {
        stopifnot(R6::is.R6(`progress`))
        self$`progress` <- `progress`
      }
    },
    toJSON = function() {
      HistoryEventObject <- list()
      if (!is.null(self$`created`)) {
        HistoryEventObject[['created']] <- self$`created`
      }
      if (!is.null(self$`description`)) {
        HistoryEventObject[['description']] <- self$`description`
      }
      if (!is.null(self$`status`)) {
        HistoryEventObject[['status']] <- self$`status`
      }
      if (!is.null(self$`progress`)) {
        HistoryEventObject[['progress']] <- self$`progress`$toJSON()
      }

      HistoryEventObject
    },
    fromJSON = function(HistoryEventObject) {
      if (!is.null(HistoryEventObject$`created`)) {
        self$`created` <- HistoryEventObject$`created`
      }
      if (!is.null(HistoryEventObject$`description`)) {
        self$`description` <- HistoryEventObject$`description`
      }
      if (!is.null(HistoryEventObject$`status`)) {
        self$`status` <- HistoryEventObject$`status`
      }
      if (!is.null(HistoryEventObject$`progress`)) {
        progressObject <- TransferTaskProgressSummary$new()
        progressObject$fromJSON(jsonlite::toJSON(HistoryEventObject$progress, auto_unbox = TRUE))
        self$`progress` <- progressObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "created": %s,
           "description": %s,
           "status": %s,
           "progress": %s
        }',
        self$`created`,
        self$`description`,
        self$`status`,
        self$`progress`$toJSON()
      )
    },
    fromJSONString = function(HistoryEventJson) {
      HistoryEventObject <- jsonlite::fromJSON(HistoryEventJson)
      self$`created` <- HistoryEventObject$`created`
      self$`description` <- HistoryEventObject$`description`
      self$`status` <- HistoryEventObject$`status`
      TransferTaskProgressSummaryObject <- TransferTaskProgressSummary$new()
      self$`progress` <- TransferTaskProgressSummaryObject$fromJSON(jsonlite::toJSON(HistoryEventObject$progress, auto_unbox = TRUE))
    }
  )
)
