# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' JobHistory Class
#'
#' @field created 
#' @field description 
#' @field status 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JobHistory <- R6::R6Class(
  'JobHistory',
  public = list(
    `created` = NULL,
    `description` = NULL,
    `status` = NULL,
    initialize = function(`created`, `description`, `status`){
      if (!missing(`created`)) {
        stopifnot(is.character(`created`), length(`created`) == 1)
        self$`created` <- `created`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
    },
    toJSON = function() {
      JobHistoryObject <- list()
      if (!is.null(self$`created`)) {
        JobHistoryObject[['created']] <- self$`created`
      }
      if (!is.null(self$`description`)) {
        JobHistoryObject[['description']] <- self$`description`
      }
      if (!is.null(self$`status`)) {
        JobHistoryObject[['status']] <- self$`status`
      }

      JobHistoryObject
    },
    fromJSON = function(JobHistoryObject) {
      if (!is.null(JobHistoryObject$`created`)) {
        self$`created` <- JobHistoryObject$`created`
      }
      if (!is.null(JobHistoryObject$`description`)) {
        self$`description` <- JobHistoryObject$`description`
      }
      if (!is.null(JobHistoryObject$`status`)) {
        self$`status` <- JobHistoryObject$`status`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "created": %s,
           "description": %s,
           "status": %s
        }',
        self$`created`,
        self$`description`,
        self$`status`
      )
    },
    fromJSONString = function(JobHistoryJson) {
      JobHistoryObject <- jsonlite::fromJSON(JobHistoryJson)
      self$`created` <- JobHistoryObject$`created`
      self$`description` <- JobHistoryObject$`description`
      self$`status` <- JobHistoryObject$`status`
    }
  )
)
