# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' JobRequest Class
#'
#' @field appId 
#' @field archive 
#' @field archivePath 
#' @field archiveSystem 
#' @field batchQueue 
#' @field inputs 
#' @field memoryPerNode 
#' @field name 
#' @field nodeCount 
#' @field notifications 
#' @field parameters 
#' @field processorsPerNode 
#' @field maxRunTime 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JobRequest <- R6::R6Class(
  'JobRequest',
  public = list(
    `appId` = NULL,
    `archive` = NULL,
    `archivePath` = NULL,
    `archiveSystem` = NULL,
    `batchQueue` = NULL,
    `inputs` = NULL,
    `memoryPerNode` = NULL,
    `name` = NULL,
    `nodeCount` = NULL,
    `notifications` = NULL,
    `parameters` = NULL,
    `processorsPerNode` = NULL,
    `maxRunTime` = NULL,
    initialize = function(`appId`, `archive`, `archivePath`, `archiveSystem`, `batchQueue`, `inputs`, `memoryPerNode`, `name`, `nodeCount`, `notifications`, `parameters`, `processorsPerNode`, `maxRunTime`){
      if (!missing(`appId`)) {
        stopifnot(is.character(`appId`), length(`appId`) == 1)
        self$`appId` <- `appId`
      }
      if (!missing(`archive`)) {
        self$`archive` <- `archive`
      }
      if (!missing(`archivePath`)) {
        stopifnot(is.character(`archivePath`), length(`archivePath`) == 1)
        self$`archivePath` <- `archivePath`
      }
      if (!missing(`archiveSystem`)) {
        stopifnot(is.character(`archiveSystem`), length(`archiveSystem`) == 1)
        self$`archiveSystem` <- `archiveSystem`
      }
      if (!missing(`batchQueue`)) {
        stopifnot(is.character(`batchQueue`), length(`batchQueue`) == 1)
        self$`batchQueue` <- `batchQueue`
      }
      if (!missing(`inputs`)) {
        stopifnot(R6::is.R6(`inputs`))
        self$`inputs` <- `inputs`
      }
      if (!missing(`memoryPerNode`)) {
        stopifnot(is.numeric(`memoryPerNode`), length(`memoryPerNode`) == 1)
        self$`memoryPerNode` <- `memoryPerNode`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`nodeCount`)) {
        stopifnot(is.numeric(`nodeCount`), length(`nodeCount`) == 1)
        self$`nodeCount` <- `nodeCount`
      }
      if (!missing(`notifications`)) {
        stopifnot(is.list(`notifications`), length(`notifications`) != 0)
        lapply(`notifications`, function(x) stopifnot(R6::is.R6(x)))
        self$`notifications` <- `notifications`
      }
      if (!missing(`parameters`)) {
        stopifnot(R6::is.R6(`parameters`))
        self$`parameters` <- `parameters`
      }
      if (!missing(`processorsPerNode`)) {
        stopifnot(is.numeric(`processorsPerNode`), length(`processorsPerNode`) == 1)
        self$`processorsPerNode` <- `processorsPerNode`
      }
      if (!missing(`maxRunTime`)) {
        stopifnot(is.character(`maxRunTime`), length(`maxRunTime`) == 1)
        self$`maxRunTime` <- `maxRunTime`
      }
    },
    toJSON = function() {
      JobRequestObject <- list()
      if (!is.null(self$`appId`)) {
        JobRequestObject[['appId']] <- self$`appId`
      }
      if (!is.null(self$`archive`)) {
        JobRequestObject[['archive']] <- self$`archive`
      }
      if (!is.null(self$`archivePath`)) {
        JobRequestObject[['archivePath']] <- self$`archivePath`
      }
      if (!is.null(self$`archiveSystem`)) {
        JobRequestObject[['archiveSystem']] <- self$`archiveSystem`
      }
      if (!is.null(self$`batchQueue`)) {
        JobRequestObject[['batchQueue']] <- self$`batchQueue`
      }
      if (!is.null(self$`inputs`)) {
        JobRequestObject[['inputs']] <- self$`inputs`$toJSON()
      }
      if (!is.null(self$`memoryPerNode`)) {
        JobRequestObject[['memoryPerNode']] <- self$`memoryPerNode`
      }
      if (!is.null(self$`name`)) {
        JobRequestObject[['name']] <- self$`name`
      }
      if (!is.null(self$`nodeCount`)) {
        JobRequestObject[['nodeCount']] <- self$`nodeCount`
      }
      if (!is.null(self$`notifications`)) {
        JobRequestObject[['notifications']] <- lapply(self$`notifications`, function(x) x$toJSON())
      }
      if (!is.null(self$`parameters`)) {
        JobRequestObject[['parameters']] <- self$`parameters`$toJSON()
      }
      if (!is.null(self$`processorsPerNode`)) {
        JobRequestObject[['processorsPerNode']] <- self$`processorsPerNode`
      }
      if (!is.null(self$`maxRunTime`)) {
        JobRequestObject[['maxRunTime']] <- self$`maxRunTime`
      }

      JobRequestObject
    },
    fromJSON = function(JobRequestJson) {
      JobRequestObject <- jsonlite::fromJSON(JobRequestJson)
      if (!is.null(JobRequestObject$`appId`)) {
        self$`appId` <- JobRequestObject$`appId`
      }
      if (!is.null(JobRequestObject$`archive`)) {
        self$`archive` <- JobRequestObject$`archive`
      }
      if (!is.null(JobRequestObject$`archivePath`)) {
        self$`archivePath` <- JobRequestObject$`archivePath`
      }
      if (!is.null(JobRequestObject$`archiveSystem`)) {
        self$`archiveSystem` <- JobRequestObject$`archiveSystem`
      }
      if (!is.null(JobRequestObject$`batchQueue`)) {
        self$`batchQueue` <- JobRequestObject$`batchQueue`
      }
      if (!is.null(JobRequestObject$`inputs`)) {
        inputsObject <- TODO_OBJECT_MAPPING$new()
        inputsObject$fromJSON(jsonlite::toJSON(JobRequestObject$inputs, auto_unbox = TRUE))
        self$`inputs` <- inputsObject
      }
      if (!is.null(JobRequestObject$`memoryPerNode`)) {
        self$`memoryPerNode` <- JobRequestObject$`memoryPerNode`
      }
      if (!is.null(JobRequestObject$`name`)) {
        self$`name` <- JobRequestObject$`name`
      }
      if (!is.null(JobRequestObject$`nodeCount`)) {
        self$`nodeCount` <- JobRequestObject$`nodeCount`
      }
      if (!is.null(JobRequestObject$`notifications`)) {
        self$`notifications` <- lapply(JobRequestObject$`notifications`, function(x) {
          notificationsObject <- Notification$new()
          notificationsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          notificationsObject
        })
      }
      if (!is.null(JobRequestObject$`parameters`)) {
        parametersObject <- TODO_OBJECT_MAPPING$new()
        parametersObject$fromJSON(jsonlite::toJSON(JobRequestObject$parameters, auto_unbox = TRUE))
        self$`parameters` <- parametersObject
      }
      if (!is.null(JobRequestObject$`processorsPerNode`)) {
        self$`processorsPerNode` <- JobRequestObject$`processorsPerNode`
      }
      if (!is.null(JobRequestObject$`maxRunTime`)) {
        self$`maxRunTime` <- JobRequestObject$`maxRunTime`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "appId": %s,
           "archive": %s,
           "archivePath": %s,
           "archiveSystem": %s,
           "batchQueue": %s,
           "inputs": %s,
           "memoryPerNode": %d,
           "name": %s,
           "nodeCount": %d,
           "notifications": [%s],
           "parameters": %s,
           "processorsPerNode": %d,
           "maxRunTime": %s
        }',
        self$`appId`,
        self$`archive`,
        self$`archivePath`,
        self$`archiveSystem`,
        self$`batchQueue`,
        self$`inputs`$toJSON(),
        self$`memoryPerNode`,
        self$`name`,
        self$`nodeCount`,
        lapply(self$`notifications`, function(x) paste(x$toJSON(), sep=",")),
        self$`parameters`$toJSON(),
        self$`processorsPerNode`,
        self$`maxRunTime`
      )
    },
    fromJSONString = function(JobRequestJson) {
      JobRequestObject <- jsonlite::fromJSON(JobRequestJson)
      self$`appId` <- JobRequestObject$`appId`
      self$`archive` <- JobRequestObject$`archive`
      self$`archivePath` <- JobRequestObject$`archivePath`
      self$`archiveSystem` <- JobRequestObject$`archiveSystem`
      self$`batchQueue` <- JobRequestObject$`batchQueue`
      TODO_OBJECT_MAPPINGObject -> TODO_OBJECT_MAPPING$new()
      self$`inputs` <- TODO_OBJECT_MAPPINGObject$fromJSON(jsonlite::toJSON(JobRequestObject$inputs, auto_unbox = TRUE))
      self$`memoryPerNode` <- JobRequestObject$`memoryPerNode`
      self$`name` <- JobRequestObject$`name`
      self$`nodeCount` <- JobRequestObject$`nodeCount`
      self$`notifications` <- lapply(JobRequestObject$`notifications`, function(x) Notification$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      TODO_OBJECT_MAPPINGObject -> TODO_OBJECT_MAPPING$new()
      self$`parameters` <- TODO_OBJECT_MAPPINGObject$fromJSON(jsonlite::toJSON(JobRequestObject$parameters, auto_unbox = TRUE))
      self$`processorsPerNode` <- JobRequestObject$`processorsPerNode`
      self$`maxRunTime` <- JobRequestObject$`maxRunTime`
    }
  )
)
