# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' MetadataSchema Class
#'
#' @field created 
#' @field internalUsername 
#' @field lastUpdated 
#' @field owner 
#' @field schema 
#' @field uuid 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MetadataSchema <- R6::R6Class(
  'MetadataSchema',
  public = list(
    `created` = NULL,
    `internalUsername` = NULL,
    `lastUpdated` = NULL,
    `owner` = NULL,
    `schema` = NULL,
    `uuid` = NULL,
    initialize = function(`created`, `internalUsername`, `lastUpdated`, `owner`, `schema`, `uuid`){
      if (!missing(`created`)) {
        stopifnot(is.character(`created`), length(`created`) == 1)
        self$`created` <- `created`
      }
      if (!missing(`internalUsername`)) {
        stopifnot(is.character(`internalUsername`), length(`internalUsername`) == 1)
        self$`internalUsername` <- `internalUsername`
      }
      if (!missing(`lastUpdated`)) {
        stopifnot(is.character(`lastUpdated`), length(`lastUpdated`) == 1)
        self$`lastUpdated` <- `lastUpdated`
      }
      if (!missing(`owner`)) {
        stopifnot(is.character(`owner`), length(`owner`) == 1)
        self$`owner` <- `owner`
      }
      if (!missing(`schema`)) {
        stopifnot(is.character(`schema`), length(`schema`) == 1)
        self$`schema` <- `schema`
      }
      if (!missing(`uuid`)) {
        stopifnot(is.character(`uuid`), length(`uuid`) == 1)
        self$`uuid` <- `uuid`
      }
    },
    toJSON = function() {
      MetadataSchemaObject <- list()
      if (!is.null(self$`created`)) {
        MetadataSchemaObject[['created']] <- self$`created`
      }
      if (!is.null(self$`internalUsername`)) {
        MetadataSchemaObject[['internalUsername']] <- self$`internalUsername`
      }
      if (!is.null(self$`lastUpdated`)) {
        MetadataSchemaObject[['lastUpdated']] <- self$`lastUpdated`
      }
      if (!is.null(self$`owner`)) {
        MetadataSchemaObject[['owner']] <- self$`owner`
      }
      if (!is.null(self$`schema`)) {
        MetadataSchemaObject[['schema']] <- self$`schema`
      }
      if (!is.null(self$`uuid`)) {
        MetadataSchemaObject[['uuid']] <- self$`uuid`
      }

      MetadataSchemaObject
    },
    fromJSON = function(MetadataSchemaObject) {
      if (!is.null(MetadataSchemaObject$`created`)) {
        self$`created` <- MetadataSchemaObject$`created`
      }
      if (!is.null(MetadataSchemaObject$`internalUsername`)) {
        self$`internalUsername` <- MetadataSchemaObject$`internalUsername`
      }
      if (!is.null(MetadataSchemaObject$`lastUpdated`)) {
        self$`lastUpdated` <- MetadataSchemaObject$`lastUpdated`
      }
      if (!is.null(MetadataSchemaObject$`owner`)) {
        self$`owner` <- MetadataSchemaObject$`owner`
      }
      if (!is.null(MetadataSchemaObject$`schema`)) {
        self$`schema` <- MetadataSchemaObject$`schema`
      }
      if (!is.null(MetadataSchemaObject$`uuid`)) {
        self$`uuid` <- MetadataSchemaObject$`uuid`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "created": %s,
           "internalUsername": %s,
           "lastUpdated": %s,
           "owner": %s,
           "schema": %s,
           "uuid": %s
        }',
        self$`created`,
        self$`internalUsername`,
        self$`lastUpdated`,
        self$`owner`,
        self$`schema`,
        self$`uuid`
      )
    },
    fromJSONString = function(MetadataSchemaJson) {
      MetadataSchemaObject <- jsonlite::fromJSON(MetadataSchemaJson)
      self$`created` <- MetadataSchemaObject$`created`
      self$`internalUsername` <- MetadataSchemaObject$`internalUsername`
      self$`lastUpdated` <- MetadataSchemaObject$`lastUpdated`
      self$`owner` <- MetadataSchemaObject$`owner`
      self$`schema` <- MetadataSchemaObject$`schema`
      self$`uuid` <- MetadataSchemaObject$`uuid`
    }
  )
)
