# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Metadata Class
#'
#' @field associationIds 
#' @field created 
#' @field internalUsername 
#' @field lastUpdated 
#' @field name 
#' @field owner 
#' @field uuid 
#' @field value 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Metadata <- R6::R6Class(
  'Metadata',
  public = list(
    `associationIds` = NULL,
    `created` = NULL,
    `internalUsername` = NULL,
    `lastUpdated` = NULL,
    `name` = NULL,
    `owner` = NULL,
    `uuid` = NULL,
    `value` = NULL,
    initialize = function(`associationIds`, `created`, `internalUsername`, `lastUpdated`, `name`, `owner`, `uuid`, `value`){
      if (!missing(`associationIds`)) {
        stopifnot(is.list(`associationIds`), length(`associationIds`) != 0)
        lapply(`associationIds`, function(x) stopifnot(is.character(x)))
        self$`associationIds` <- `associationIds`
      }
      if (!missing(`created`)) {
        stopifnot(is.character(`created`), length(`created`) == 1)
        self$`created` <- `created`
      }
      if (!missing(`internalUsername`)) {
        stopifnot(is.character(`internalUsername`), length(`internalUsername`) == 1)
        self$`internalUsername` <- `internalUsername`
      }
      if (!missing(`lastUpdated`)) {
        stopifnot(is.character(`lastUpdated`), length(`lastUpdated`) == 1)
        self$`lastUpdated` <- `lastUpdated`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`owner`)) {
        stopifnot(is.character(`owner`), length(`owner`) == 1)
        self$`owner` <- `owner`
      }
      if (!missing(`uuid`)) {
        stopifnot(is.character(`uuid`), length(`uuid`) == 1)
        self$`uuid` <- `uuid`
      }
      if (!missing(`value`)) {
        stopifnot(is.character(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      MetadataObject <- list()
      if (!is.null(self$`associationIds`)) {
        MetadataObject[['associationIds']] <- self$`associationIds`
      }
      if (!is.null(self$`created`)) {
        MetadataObject[['created']] <- self$`created`
      }
      if (!is.null(self$`internalUsername`)) {
        MetadataObject[['internalUsername']] <- self$`internalUsername`
      }
      if (!is.null(self$`lastUpdated`)) {
        MetadataObject[['lastUpdated']] <- self$`lastUpdated`
      }
      if (!is.null(self$`name`)) {
        MetadataObject[['name']] <- self$`name`
      }
      if (!is.null(self$`owner`)) {
        MetadataObject[['owner']] <- self$`owner`
      }
      if (!is.null(self$`uuid`)) {
        MetadataObject[['uuid']] <- self$`uuid`
      }
      if (!is.null(self$`value`)) {
        MetadataObject[['value']] <- self$`value`
      }

      MetadataObject
    },
    fromJSON = function(MetadataJson) {
      MetadataObject <- jsonlite::fromJSON(MetadataJson)
      if (!is.null(MetadataObject$`associationIds`)) {
        self$`associationIds` <- MetadataObject$`associationIds`
      }
      if (!is.null(MetadataObject$`created`)) {
        self$`created` <- MetadataObject$`created`
      }
      if (!is.null(MetadataObject$`internalUsername`)) {
        self$`internalUsername` <- MetadataObject$`internalUsername`
      }
      if (!is.null(MetadataObject$`lastUpdated`)) {
        self$`lastUpdated` <- MetadataObject$`lastUpdated`
      }
      if (!is.null(MetadataObject$`name`)) {
        self$`name` <- MetadataObject$`name`
      }
      if (!is.null(MetadataObject$`owner`)) {
        self$`owner` <- MetadataObject$`owner`
      }
      if (!is.null(MetadataObject$`uuid`)) {
        self$`uuid` <- MetadataObject$`uuid`
      }
      if (!is.null(MetadataObject$`value`)) {
        self$`value` <- MetadataObject$`value`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "associationIds": [%s],
           "created": %s,
           "internalUsername": %s,
           "lastUpdated": %s,
           "name": %s,
           "owner": %s,
           "uuid": %s,
           "value": %s
        }',
        lapply(self$`associationIds`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`created`,
        self$`internalUsername`,
        self$`lastUpdated`,
        self$`name`,
        self$`owner`,
        self$`uuid`,
        self$`value`
      )
    },
    fromJSONString = function(MetadataJson) {
      MetadataObject <- jsonlite::fromJSON(MetadataJson)
      self$`associationIds` <- MetadataObject$`associationIds`
      self$`created` <- MetadataObject$`created`
      self$`internalUsername` <- MetadataObject$`internalUsername`
      self$`lastUpdated` <- MetadataObject$`lastUpdated`
      self$`name` <- MetadataObject$`name`
      self$`owner` <- MetadataObject$`owner`
      self$`uuid` <- MetadataObject$`uuid`
      self$`value` <- MetadataObject$`value`
    }
  )
)
