# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ProfileRequest Class
#'
#' @field username 
#' @field email 
#' @field city 
#' @field country 
#' @field department 
#' @field fax 
#' @field firstName 
#' @field gender 
#' @field institution 
#' @field lastName 
#' @field phone 
#' @field position 
#' @field researchArea 
#' @field state 
#' @field status 
#' @field password 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ProfileRequest <- R6::R6Class(
  'ProfileRequest',
  public = list(
    `username` = NULL,
    `email` = NULL,
    `city` = NULL,
    `country` = NULL,
    `department` = NULL,
    `fax` = NULL,
    `firstName` = NULL,
    `gender` = NULL,
    `institution` = NULL,
    `lastName` = NULL,
    `phone` = NULL,
    `position` = NULL,
    `researchArea` = NULL,
    `state` = NULL,
    `status` = NULL,
    `password` = NULL,
    initialize = function(`username`, `email`, `city`, `country`, `department`, `fax`, `firstName`, `gender`, `institution`, `lastName`, `phone`, `position`, `researchArea`, `state`, `status`, `password`){
      if (!missing(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!missing(`city`)) {
        stopifnot(is.character(`city`), length(`city`) == 1)
        self$`city` <- `city`
      }
      if (!missing(`country`)) {
        stopifnot(is.character(`country`), length(`country`) == 1)
        self$`country` <- `country`
      }
      if (!missing(`department`)) {
        stopifnot(is.character(`department`), length(`department`) == 1)
        self$`department` <- `department`
      }
      if (!missing(`fax`)) {
        stopifnot(is.character(`fax`), length(`fax`) == 1)
        self$`fax` <- `fax`
      }
      if (!missing(`firstName`)) {
        stopifnot(is.character(`firstName`), length(`firstName`) == 1)
        self$`firstName` <- `firstName`
      }
      if (!missing(`gender`)) {
        stopifnot(R6::is.R6(`gender`))
        self$`gender` <- `gender`
      }
      if (!missing(`institution`)) {
        stopifnot(is.character(`institution`), length(`institution`) == 1)
        self$`institution` <- `institution`
      }
      if (!missing(`lastName`)) {
        stopifnot(is.character(`lastName`), length(`lastName`) == 1)
        self$`lastName` <- `lastName`
      }
      if (!missing(`phone`)) {
        stopifnot(is.character(`phone`), length(`phone`) == 1)
        self$`phone` <- `phone`
      }
      if (!missing(`position`)) {
        stopifnot(is.character(`position`), length(`position`) == 1)
        self$`position` <- `position`
      }
      if (!missing(`researchArea`)) {
        stopifnot(is.character(`researchArea`), length(`researchArea`) == 1)
        self$`researchArea` <- `researchArea`
      }
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`password`)) {
        stopifnot(is.character(`password`), length(`password`) == 1)
        self$`password` <- `password`
      }
    },
    toJSON = function() {
      ProfileRequestObject <- list()
      if (!is.null(self$`username`)) {
        ProfileRequestObject[['username']] <- self$`username`
      }
      if (!is.null(self$`email`)) {
        ProfileRequestObject[['email']] <- self$`email`
      }
      if (!is.null(self$`city`)) {
        ProfileRequestObject[['city']] <- self$`city`
      }
      if (!is.null(self$`country`)) {
        ProfileRequestObject[['country']] <- self$`country`
      }
      if (!is.null(self$`department`)) {
        ProfileRequestObject[['department']] <- self$`department`
      }
      if (!is.null(self$`fax`)) {
        ProfileRequestObject[['fax']] <- self$`fax`
      }
      if (!is.null(self$`firstName`)) {
        ProfileRequestObject[['firstName']] <- self$`firstName`
      }
      if (!is.null(self$`gender`)) {
        ProfileRequestObject[['gender']] <- self$`gender`$toJSON()
      }
      if (!is.null(self$`institution`)) {
        ProfileRequestObject[['institution']] <- self$`institution`
      }
      if (!is.null(self$`lastName`)) {
        ProfileRequestObject[['lastName']] <- self$`lastName`
      }
      if (!is.null(self$`phone`)) {
        ProfileRequestObject[['phone']] <- self$`phone`
      }
      if (!is.null(self$`position`)) {
        ProfileRequestObject[['position']] <- self$`position`
      }
      if (!is.null(self$`researchArea`)) {
        ProfileRequestObject[['researchArea']] <- self$`researchArea`
      }
      if (!is.null(self$`state`)) {
        ProfileRequestObject[['state']] <- self$`state`
      }
      if (!is.null(self$`status`)) {
        ProfileRequestObject[['status']] <- self$`status`
      }
      if (!is.null(self$`password`)) {
        ProfileRequestObject[['password']] <- self$`password`
      }

      ProfileRequestObject
    },
    fromJSON = function(ProfileRequestJson) {
      ProfileRequestObject <- jsonlite::fromJSON(ProfileRequestJson)
      if (!is.null(ProfileRequestObject$`username`)) {
        self$`username` <- ProfileRequestObject$`username`
      }
      if (!is.null(ProfileRequestObject$`email`)) {
        self$`email` <- ProfileRequestObject$`email`
      }
      if (!is.null(ProfileRequestObject$`city`)) {
        self$`city` <- ProfileRequestObject$`city`
      }
      if (!is.null(ProfileRequestObject$`country`)) {
        self$`country` <- ProfileRequestObject$`country`
      }
      if (!is.null(ProfileRequestObject$`department`)) {
        self$`department` <- ProfileRequestObject$`department`
      }
      if (!is.null(ProfileRequestObject$`fax`)) {
        self$`fax` <- ProfileRequestObject$`fax`
      }
      if (!is.null(ProfileRequestObject$`firstName`)) {
        self$`firstName` <- ProfileRequestObject$`firstName`
      }
      if (!is.null(ProfileRequestObject$`gender`)) {
        genderObject <- Gender$new()
        genderObject$fromJSON(jsonlite::toJSON(ProfileRequestObject$gender, auto_unbox = TRUE))
        self$`gender` <- genderObject
      }
      if (!is.null(ProfileRequestObject$`institution`)) {
        self$`institution` <- ProfileRequestObject$`institution`
      }
      if (!is.null(ProfileRequestObject$`lastName`)) {
        self$`lastName` <- ProfileRequestObject$`lastName`
      }
      if (!is.null(ProfileRequestObject$`phone`)) {
        self$`phone` <- ProfileRequestObject$`phone`
      }
      if (!is.null(ProfileRequestObject$`position`)) {
        self$`position` <- ProfileRequestObject$`position`
      }
      if (!is.null(ProfileRequestObject$`researchArea`)) {
        self$`researchArea` <- ProfileRequestObject$`researchArea`
      }
      if (!is.null(ProfileRequestObject$`state`)) {
        self$`state` <- ProfileRequestObject$`state`
      }
      if (!is.null(ProfileRequestObject$`status`)) {
        self$`status` <- ProfileRequestObject$`status`
      }
      if (!is.null(ProfileRequestObject$`password`)) {
        self$`password` <- ProfileRequestObject$`password`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "username": %s,
           "email": %s,
           "city": %s,
           "country": %s,
           "department": %s,
           "fax": %s,
           "firstName": %s,
           "gender": %s,
           "institution": %s,
           "lastName": %s,
           "phone": %s,
           "position": %s,
           "researchArea": %s,
           "state": %s,
           "status": %s,
           "password": %s
        }',
        self$`username`,
        self$`email`,
        self$`city`,
        self$`country`,
        self$`department`,
        self$`fax`,
        self$`firstName`,
        self$`gender`$toJSON(),
        self$`institution`,
        self$`lastName`,
        self$`phone`,
        self$`position`,
        self$`researchArea`,
        self$`state`,
        self$`status`,
        self$`password`
      )
    },
    fromJSONString = function(ProfileRequestJson) {
      ProfileRequestObject <- jsonlite::fromJSON(ProfileRequestJson)
      self$`username` <- ProfileRequestObject$`username`
      self$`email` <- ProfileRequestObject$`email`
      self$`city` <- ProfileRequestObject$`city`
      self$`country` <- ProfileRequestObject$`country`
      self$`department` <- ProfileRequestObject$`department`
      self$`fax` <- ProfileRequestObject$`fax`
      self$`firstName` <- ProfileRequestObject$`firstName`
      GenderObject -> Gender$new()
      self$`gender` <- GenderObject$fromJSON(jsonlite::toJSON(ProfileRequestObject$gender, auto_unbox = TRUE))
      self$`institution` <- ProfileRequestObject$`institution`
      self$`lastName` <- ProfileRequestObject$`lastName`
      self$`phone` <- ProfileRequestObject$`phone`
      self$`position` <- ProfileRequestObject$`position`
      self$`researchArea` <- ProfileRequestObject$`researchArea`
      self$`state` <- ProfileRequestObject$`state`
      self$`status` <- ProfileRequestObject$`status`
      self$`password` <- ProfileRequestObject$`password`
    }
  )
)
