# Agave Platform Science API
#
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
#
# OpenAPI spec version: 2.2.14
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' @title Profiles operations
#' @description rAgave.Profiles
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' add_internal_user
#'
#'
#' add_profile
#'
#'
#' clear_internal_users
#'
#'
#' delete_internal_user
#'
#'
#' delete_profile
#'
#'
#' get_internal_user
#'
#'
#' get_profile
#'
#'
#' list_internal_users
#'
#'
#' list_profiles
#'
#'
#' update_internal_user
#'
#'
#' update_profile
#'
#' }
#'
#' @export
ProfilesApi <- R6::R6Class(
  'ProfilesApi',
  private = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    responseType = 'list',
    formatResponse = function(resp, args=list()) {
      
      # read the args from the unnamed request args
      responseType = getElement(args, 'responseType')
      
      if (is.null(responseType) || nchar(responseType) == 0) {
        responseType = private$responseType
      }
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        logger.debug(jsonlite::toJSON(httr::content(resp,stringsAsFactors = FALSE), auto_unbox=TRUE, null="null", na="null"))
        
        if (responseType == 'raw') {
          httr::content(resp, 'text', encode="UTF-8")
        }
        else {
          jsonResp <- httr::content(resp)
          if ("result" %in% names(jsonResp)) {
            jsonResp <- jsonResp$result
          }
          
          if (responseType == 'df' && length(jsonResp) > 0) {
            # convert to a list of dataframes
            do.call("rbind", lapply(jsonResp, as.data.frame, col.names=factor(names(jsonResp[[1]]))))
          }
          else {
            jsonResp
          }
        }
        
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        logger.warn(jsonlite::toJSON(httr::content(resp), auto_unbox=TRUE, null="null", na="null"))
        httr::content(resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        logger.warn(jsonlite::toJSON(httr::content(resp), auto_unbox=TRUE, null="null", na="null"))
        httr::content(resp)
      }
    }
  ),
  public = list(
    initialize = function(apiClient, responseType){
      if (!missing(apiClient)) {
        private$apiClient <- apiClient
      }
      else {
        private$apiClient <- ApiClient$new()
      }
      
      if (missing(responseType) || is.null(responseType) || nchar(responseType) == 0) {
        # we ignore and use the default
      }
      else if (responseType != 'raw' && responseType != 'list' && responseType != 'df') {
        stop("Invalid responseType. Please specify one of: raw, list, df") 
      }
      else {
        # set the response type to the class default to be used
        # whenever it is not explicitly set on a request
        private$responseType = responseType
      }
    },
    addProfile = function(body, naked, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`naked`)) {
        queryParams['naked'] <- naked
      }


      if (!missing(`body`)) {
        if (!is.list(`body`)) {
          body <- `body`$toJSON()
        }
      } else {
        body <- NULL
      }

      urlPath <- "/profiles/v2"
      resp <- private$apiClient$callApi(url = paste0(private$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      private$formatResponse(resp, args);
    },
    deleteProfile = function(username, naked, filter, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`filter`)) {
        queryParams['filter'] <- filter
      }

      if (!missing(`naked`)) {
        queryParams['naked'] <- naked
      }

      urlPath <- "/profiles/v2/{apiUsername}"
      if (!missing(`username`)) {
        urlPath <- gsub(paste0("\\{", "apiUsername", "\\}"), `username`, urlPath)
      }

      resp <- private$apiClient$callApi(url = paste0(private$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      private$formatResponse(resp, args);
    },
    getProfile = function(username="me", naked, filter, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`filter`)) {
        queryParams['filter'] <- filter
      }

      if (!missing(`naked`)) {
        queryParams['naked'] <- naked
      }

      if (missing(username) || is.null(username) || nchar(username) == 0) {
        username <- "me"
      }

      urlPath <- "/profiles/v2/{apiUsername}"
      if (!missing(`username`)) {
        urlPath <- gsub(paste0("\\{", "apiUsername", "\\}"), `username`, urlPath)
      }

      resp <- private$apiClient$callApi(url = paste0(private$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      private$formatResponse(resp, args);
    },
    listProfiles = function(naked, username, name, email, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`username`)) {
        queryParams['username'] <- username
      }

      if (!missing(`name`)) {
        queryParams['name'] <- name
      }

      if (!missing(`email`)) {
        queryParams['email'] <- email
      }

      if (!missing(`naked`)) {
        queryParams['naked'] <- naked
      }

      urlPath <- "/profiles/v2"
      resp <- private$apiClient$callApi(url = paste0(private$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      private$formatResponse(resp, args)
    },
    updateProfile = function(username, body, naked, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`naked`)) {
        queryParams['naked'] <- naked
      }
      
      if (!missing(`body`)) {
        if (!is.list(`body`)) {
          body <- `body`$toJSON()
        }
      } else {
        body <- NULL
      }

      urlPath <- "/profiles/v2/{apiUsername}"
      if (!missing(`username`)) {
        urlPath <- gsub(paste0("\\{", "apiUsername", "\\}"), `username`, urlPath)
      }

      resp <- private$apiClient$callApi(url = paste0(private$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      private$formatResponse(resp, args);
    }
  )
)
