# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SinglePostItResponse Class
#'
#' @field message 
#' @field result 
#' @field status 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SinglePostItResponse <- R6::R6Class(
  'SinglePostItResponse',
  public = list(
    `message` = NULL,
    `result` = NULL,
    `status` = NULL,
    initialize = function(`message`, `result`, `status`){
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`result`)) {
        stopifnot(R6::is.R6(`result`))
        self$`result` <- `result`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
    },
    toJSON = function() {
      SinglePostItResponseObject <- list()
      if (!is.null(self$`message`)) {
        SinglePostItResponseObject[['message']] <- self$`message`
      }
      if (!is.null(self$`result`)) {
        SinglePostItResponseObject[['result']] <- self$`result`$toJSON()
      }
      if (!is.null(self$`status`)) {
        SinglePostItResponseObject[['status']] <- self$`status`
      }

      SinglePostItResponseObject
    },
    fromJSON = function(SinglePostItResponseJson) {
      SinglePostItResponseObject <- jsonlite::fromJSON(SinglePostItResponseJson)
      if (!is.null(SinglePostItResponseObject$`message`)) {
        self$`message` <- SinglePostItResponseObject$`message`
      }
      if (!is.null(SinglePostItResponseObject$`result`)) {
        resultObject <- PostIt$new()
        resultObject$fromJSON(jsonlite::toJSON(SinglePostItResponseObject$result, auto_unbox = TRUE))
        self$`result` <- resultObject
      }
      if (!is.null(SinglePostItResponseObject$`status`)) {
        self$`status` <- SinglePostItResponseObject$`status`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "message": %s,
           "result": %s,
           "status": %s
        }',
        self$`message`,
        self$`result`$toJSON(),
        self$`status`
      )
    },
    fromJSONString = function(SinglePostItResponseJson) {
      SinglePostItResponseObject <- jsonlite::fromJSON(SinglePostItResponseJson)
      self$`message` <- SinglePostItResponseObject$`message`
      PostItObject -> PostIt$new()
      self$`result` <- PostItObject$fromJSON(jsonlite::toJSON(SinglePostItResponseObject$result, auto_unbox = TRUE))
      self$`status` <- SinglePostItResponseObject$`status`
    }
  )
)
