# Agave Platform Science API
#
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
#
# Agave Platform version: 2.2.14
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SingleProfileResponse Class
#'
#' 
#'
#' @field message success or failure
#' @field result 
#' @field status success or failure
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SingleProfileResponse <- R6::R6Class(
  'SingleProfileResponse',
  public = list(
    `message` = NULL,
    `result` = NULL,
    `status` = NULL,
    initialize = function(`message`, `result`, `status`){
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`result`)) {
        stopifnot(R6::is.R6(`result`))
        self$`result` <- `result`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
    },
    asJSON = function() {
      self$toJSON()
    },
    toJSON = function() {
      SingleProfileResponseObject <- list()
      if (!is.null(self$`message`)) {
        SingleProfileResponseObject[['message']] <- self$`message`
      }
      else {
        SingleProfileResponseObject[['message']] <- NULL
      }
      if (!is.null(self$`result`)) {
        SingleProfileResponseObject[['result']] <- self$`result`$toJSON()
      }
      else {
        SingleProfileResponseObject[['result']] <- NULL
      }
      if (!is.null(self$`status`)) {
        SingleProfileResponseObject[['status']] <- self$`status`
      }
      else {
        SingleProfileResponseObject[['status']] <- NULL
      }

      SingleProfileResponseObject
    },
    fromJSON = function(SingleProfileResponseObject) {
      if (is.character(SingleProfileResponseObject)) {
        SingleProfileResponseObject <- jsonlite::fromJSON(SingleProfileResponseJson)
      }

      if ("result" %in% names(SingleProfileResponseObject)) {
        SingleProfileResponseObject <- SingleProfileResponseObject$result
      }

      if (!is.null(SingleProfileResponseObject$`message`)) {
        self$`message` <- SingleProfileResponseObject$`message`
      }
      if (!is.null(SingleProfileResponseObject$`result`)) {
        resultObject <- Profile$new()
        resultObject$fromJSON(jsonlite::toJSON(SingleProfileResponseObject$result, auto_unbox = TRUE))
        self$`result` <- resultObject
      }
      if (!is.null(SingleProfileResponseObject$`status`)) {
        self$`status` <- SingleProfileResponseObject$`status`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "message": %s,
           "result": %s,
           "status": %s
        }',
        ifelse( is.null(self$`message`),"null",paste0(c('"', self$`message`, '"'))),
        self$`result`$toJSON(),
        ifelse( is.null(self$`status`),"null",paste0(c('"', self$`status`, '"')))
      )
    },
    fromJSONString = function(SingleProfileResponseJson) {
      SingleProfileResponseObject <- jsonlite::fromJSON(SingleProfileResponseJson)
      self::fromJSON(SingleProfileResponseObject)

    }
  )
)
