# Agave Platform Science API
#
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
#
# Agave Platform version: 2.2.14
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SingleClientResponse Class
#'
#' 
#'
#' @field message success or failure
#' @field result 
#' @field status success or failure
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SingleClientResponse <- R6::R6Class(
  'SingleClientResponse',
  public = list(
    `message` = NULL,
    `result` = NULL,
    `status` = NULL,
    initialize = function(`message`, `result`, `status`){
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`result`)) {
        stopifnot(R6::is.R6(`result`))
        self$`result` <- `result`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
    },
    asJSON = function() {
      self$toJSON()
    },
    toJSON = function() {
      SingleClientResponseObject <- list()
      if (!is.null(self$`message`)) {
        SingleClientResponseObject[['message']] <- self$`message`
      }
      else {
        SingleClientResponseObject[['message']] <- NULL
      }
      if (!is.null(self$`result`)) {
        SingleClientResponseObject[['result']] <- self$`result`$toJSON()
      }
      else {
        SingleClientResponseObject[['result']] <- NULL
      }
      if (!is.null(self$`status`)) {
        SingleClientResponseObject[['status']] <- self$`status`
      }
      else {
        SingleClientResponseObject[['status']] <- NULL
      }

      SingleClientResponseObject
    },
    fromJSON = function(SingleClientResponseObject) {
      if (is.character(SingleClientResponseObject)) {
        SingleClientResponseObject <- jsonlite::fromJSON(SingleClientResponseJson)
      }

      if ("result" %in% names(SingleClientResponseObject)) {
        SingleClientResponseObject <- SingleClientResponseObject$result
      }

      if (!is.null(SingleClientResponseObject$`message`)) {
        self$`message` <- SingleClientResponseObject$`message`
      }
      if (!is.null(SingleClientResponseObject$`result`)) {
        resultObject <- Client$new()
        resultObject$fromJSON(jsonlite::toJSON(SingleClientResponseObject$result, auto_unbox = TRUE))
        self$`result` <- resultObject
      }
      if (!is.null(SingleClientResponseObject$`status`)) {
        self$`status` <- SingleClientResponseObject$`status`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "message": %s,
           "result": %s,
           "status": %s
        }',
        ifelse( is.null(self$`message`),"null",paste0(c('"', self$`message`, '"'))),
        self$`result`$toJSON(),
        ifelse( is.null(self$`status`),"null",paste0(c('"', self$`status`, '"')))
      )
    },
    fromJSONString = function(SingleClientResponseJson) {
      SingleClientResponseObject <- jsonlite::fromJSON(SingleClientResponseJson)
      self::fromJSON(SingleClientResponseObject)

    }
  )
)
