# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SystemCredential Class
#'
#' @field credential 
#' @field expirationDate 
#' @field internalUsername 
#' @field isDefault 
#' @field parentType 
#' @field password 
#' @field publicKey 
#' @field privateKey 
#' @field server 
#' @field type 
#' @field username 
#' @field valid 
#' @field caCerts 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SystemCredential <- R6::R6Class(
  'SystemCredential',
  public = list(
    `credential` = NULL,
    `expirationDate` = NULL,
    `internalUsername` = NULL,
    `isDefault` = NULL,
    `parentType` = NULL,
    `password` = NULL,
    `publicKey` = NULL,
    `privateKey` = NULL,
    `server` = NULL,
    `type` = NULL,
    `username` = NULL,
    `valid` = NULL,
    `caCerts` = NULL,
    initialize = function(`credential`, `expirationDate`, `internalUsername`, `isDefault`, `parentType`, `password`, `publicKey`, `privateKey`, `server`, `type`, `username`, `valid`, `caCerts`){
      if (!missing(`credential`)) {
        stopifnot(is.character(`credential`), length(`credential`) == 1)
        self$`credential` <- `credential`
      }
      if (!missing(`expirationDate`)) {
        stopifnot(is.character(`expirationDate`), length(`expirationDate`) == 1)
        self$`expirationDate` <- `expirationDate`
      }
      if (!missing(`internalUsername`)) {
        stopifnot(is.character(`internalUsername`), length(`internalUsername`) == 1)
        self$`internalUsername` <- `internalUsername`
      }
      if (!missing(`isDefault`)) {
        self$`isDefault` <- `isDefault`
      }
      if (!missing(`parentType`)) {
        stopifnot(R6::is.R6(`parentType`))
        self$`parentType` <- `parentType`
      }
      if (!missing(`password`)) {
        stopifnot(is.character(`password`), length(`password`) == 1)
        self$`password` <- `password`
      }
      if (!missing(`publicKey`)) {
        stopifnot(is.character(`publicKey`), length(`publicKey`) == 1)
        self$`publicKey` <- `publicKey`
      }
      if (!missing(`privateKey`)) {
        stopifnot(is.character(`privateKey`), length(`privateKey`) == 1)
        self$`privateKey` <- `privateKey`
      }
      if (!missing(`server`)) {
        stopifnot(R6::is.R6(`server`))
        self$`server` <- `server`
      }
      if (!missing(`type`)) {
        stopifnot(R6::is.R6(`type`))
        self$`type` <- `type`
      }
      if (!missing(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
      if (!missing(`valid`)) {
        self$`valid` <- `valid`
      }
      if (!missing(`caCerts`)) {
        stopifnot(is.character(`caCerts`), length(`caCerts`) == 1)
        self$`caCerts` <- `caCerts`
      }
    },
    toJSON = function() {
      SystemCredentialObject <- list()
      if (!is.null(self$`credential`)) {
        SystemCredentialObject[['credential']] <- self$`credential`
      }
      if (!is.null(self$`expirationDate`)) {
        SystemCredentialObject[['expirationDate']] <- self$`expirationDate`
      }
      if (!is.null(self$`internalUsername`)) {
        SystemCredentialObject[['internalUsername']] <- self$`internalUsername`
      }
      if (!is.null(self$`isDefault`)) {
        SystemCredentialObject[['isDefault']] <- self$`isDefault`
      }
      if (!is.null(self$`parentType`)) {
        SystemCredentialObject[['parentType']] <- self$`parentType`$toJSON()
      }
      if (!is.null(self$`password`)) {
        SystemCredentialObject[['password']] <- self$`password`
      }
      if (!is.null(self$`publicKey`)) {
        SystemCredentialObject[['publicKey']] <- self$`publicKey`
      }
      if (!is.null(self$`privateKey`)) {
        SystemCredentialObject[['privateKey']] <- self$`privateKey`
      }
      if (!is.null(self$`server`)) {
        SystemCredentialObject[['server']] <- self$`server`$toJSON()
      }
      if (!is.null(self$`type`)) {
        SystemCredentialObject[['type']] <- self$`type`$toJSON()
      }
      if (!is.null(self$`username`)) {
        SystemCredentialObject[['username']] <- self$`username`
      }
      if (!is.null(self$`valid`)) {
        SystemCredentialObject[['valid']] <- self$`valid`
      }
      if (!is.null(self$`caCerts`)) {
        SystemCredentialObject[['caCerts']] <- self$`caCerts`
      }

      SystemCredentialObject
    },
    fromJSON = function(SystemCredentialJson) {
      SystemCredentialObject <- jsonlite::fromJSON(SystemCredentialJson)
      if (!is.null(SystemCredentialObject$`credential`)) {
        self$`credential` <- SystemCredentialObject$`credential`
      }
      if (!is.null(SystemCredentialObject$`expirationDate`)) {
        self$`expirationDate` <- SystemCredentialObject$`expirationDate`
      }
      if (!is.null(SystemCredentialObject$`internalUsername`)) {
        self$`internalUsername` <- SystemCredentialObject$`internalUsername`
      }
      if (!is.null(SystemCredentialObject$`isDefault`)) {
        self$`isDefault` <- SystemCredentialObject$`isDefault`
      }
      if (!is.null(SystemCredentialObject$`parentType`)) {
        parentTypeObject <- SystemType$new()
        parentTypeObject$fromJSON(jsonlite::toJSON(SystemCredentialObject$parentType, auto_unbox = TRUE))
        self$`parentType` <- parentTypeObject
      }
      if (!is.null(SystemCredentialObject$`password`)) {
        self$`password` <- SystemCredentialObject$`password`
      }
      if (!is.null(SystemCredentialObject$`publicKey`)) {
        self$`publicKey` <- SystemCredentialObject$`publicKey`
      }
      if (!is.null(SystemCredentialObject$`privateKey`)) {
        self$`privateKey` <- SystemCredentialObject$`privateKey`
      }
      if (!is.null(SystemCredentialObject$`server`)) {
        serverObject <- SystemAuthConfigServerProtocolType$new()
        serverObject$fromJSON(jsonlite::toJSON(SystemCredentialObject$server, auto_unbox = TRUE))
        self$`server` <- serverObject
      }
      if (!is.null(SystemCredentialObject$`type`)) {
        typeObject <- AuthenticationType$new()
        typeObject$fromJSON(jsonlite::toJSON(SystemCredentialObject$type, auto_unbox = TRUE))
        self$`type` <- typeObject
      }
      if (!is.null(SystemCredentialObject$`username`)) {
        self$`username` <- SystemCredentialObject$`username`
      }
      if (!is.null(SystemCredentialObject$`valid`)) {
        self$`valid` <- SystemCredentialObject$`valid`
      }
      if (!is.null(SystemCredentialObject$`caCerts`)) {
        self$`caCerts` <- SystemCredentialObject$`caCerts`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "credential": %s,
           "expirationDate": %s,
           "internalUsername": %s,
           "isDefault": %s,
           "parentType": %s,
           "password": %s,
           "publicKey": %s,
           "privateKey": %s,
           "server": %s,
           "type": %s,
           "username": %s,
           "valid": %s,
           "caCerts": %s
        }',
        self$`credential`,
        self$`expirationDate`,
        self$`internalUsername`,
        self$`isDefault`,
        self$`parentType`$toJSON(),
        self$`password`,
        self$`publicKey`,
        self$`privateKey`,
        self$`server`$toJSON(),
        self$`type`$toJSON(),
        self$`username`,
        self$`valid`,
        self$`caCerts`
      )
    },
    fromJSONString = function(SystemCredentialJson) {
      SystemCredentialObject <- jsonlite::fromJSON(SystemCredentialJson)
      self$`credential` <- SystemCredentialObject$`credential`
      self$`expirationDate` <- SystemCredentialObject$`expirationDate`
      self$`internalUsername` <- SystemCredentialObject$`internalUsername`
      self$`isDefault` <- SystemCredentialObject$`isDefault`
      SystemTypeObject -> SystemType$new()
      self$`parentType` <- SystemTypeObject$fromJSON(jsonlite::toJSON(SystemCredentialObject$parentType, auto_unbox = TRUE))
      self$`password` <- SystemCredentialObject$`password`
      self$`publicKey` <- SystemCredentialObject$`publicKey`
      self$`privateKey` <- SystemCredentialObject$`privateKey`
      SystemAuthConfigServerProtocolTypeObject -> SystemAuthConfigServerProtocolType$new()
      self$`server` <- SystemAuthConfigServerProtocolTypeObject$fromJSON(jsonlite::toJSON(SystemCredentialObject$server, auto_unbox = TRUE))
      AuthenticationTypeObject -> AuthenticationType$new()
      self$`type` <- AuthenticationTypeObject$fromJSON(jsonlite::toJSON(SystemCredentialObject$type, auto_unbox = TRUE))
      self$`username` <- SystemCredentialObject$`username`
      self$`valid` <- SystemCredentialObject$`valid`
      self$`caCerts` <- SystemCredentialObject$`caCerts`
    }
  )
)
