# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SystemRole Class
#'
#' @field username 
#' @field role 
#' @field created 
#' @field lastUpdated 
#' @field id 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SystemRole <- R6::R6Class(
  'SystemRole',
  public = list(
    `username` = NULL,
    `role` = NULL,
    `created` = NULL,
    `lastUpdated` = NULL,
    `id` = NULL,
    initialize = function(`username`, `role`, `created`, `lastUpdated`, `id`){
      if (!missing(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
      if (!missing(`role`)) {
        stopifnot(R6::is.R6(`role`))
        self$`role` <- `role`
      }
      if (!missing(`created`)) {
        stopifnot(is.character(`created`), length(`created`) == 1)
        self$`created` <- `created`
      }
      if (!missing(`lastUpdated`)) {
        stopifnot(is.character(`lastUpdated`), length(`lastUpdated`) == 1)
        self$`lastUpdated` <- `lastUpdated`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      SystemRoleObject <- list()
      if (!is.null(self$`username`)) {
        SystemRoleObject[['username']] <- self$`username`
      }
      if (!is.null(self$`role`)) {
        SystemRoleObject[['role']] <- self$`role`$toJSON()
      }
      if (!is.null(self$`created`)) {
        SystemRoleObject[['created']] <- self$`created`
      }
      if (!is.null(self$`lastUpdated`)) {
        SystemRoleObject[['lastUpdated']] <- self$`lastUpdated`
      }
      if (!is.null(self$`id`)) {
        SystemRoleObject[['id']] <- self$`id`
      }

      SystemRoleObject
    },
    fromJSON = function(SystemRoleObject) {
      if (!is.null(SystemRoleObject$`username`)) {
        self$`username` <- SystemRoleObject$`username`
      }
      if (!is.null(SystemRoleObject$`role`)) {
        roleObject <- SystemRoleType$new()
        roleObject$fromJSON(jsonlite::toJSON(SystemRoleObject$role, auto_unbox = TRUE))
        self$`role` <- roleObject
      }
      if (!is.null(SystemRoleObject$`created`)) {
        self$`created` <- SystemRoleObject$`created`
      }
      if (!is.null(SystemRoleObject$`lastUpdated`)) {
        self$`lastUpdated` <- SystemRoleObject$`lastUpdated`
      }
      if (!is.null(SystemRoleObject$`id`)) {
        self$`id` <- SystemRoleObject$`id`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "username": %s,
           "role": %s,
           "created": %s,
           "lastUpdated": %s,
           "id": %s
        }',
        self$`username`,
        self$`role`$toJSON(),
        self$`created`,
        self$`lastUpdated`,
        self$`id`
      )
    },
    fromJSONString = function(SystemRoleJson) {
      SystemRoleObject <- jsonlite::fromJSON(SystemRoleJson)
      self$`username` <- SystemRoleObject$`username`
      SystemRoleTypeObject <- SystemRoleType$new()
      self$`role` <- SystemRoleTypeObject$fromJSON(jsonlite::toJSON(SystemRoleObject$role, auto_unbox = TRUE))
      self$`created` <- SystemRoleObject$`created`
      self$`lastUpdated` <- SystemRoleObject$`lastUpdated`
      self$`id` <- SystemRoleObject$`id`
    }
  )
)
