# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SystemAuthConfig Class
#'
#' @field credential 
#' @field internalUsername 
#' @field password 
#' @field publicKey 
#' @field privateKey 
#' @field server 
#' @field type 
#' @field username 
#' @field caCerts 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SystemAuthConfig <- R6::R6Class(
  'SystemAuthConfig',
  public = list(
    `credential` = NULL,
    `internalUsername` = NULL,
    `password` = NULL,
    `publicKey` = NULL,
    `privateKey` = NULL,
    `server` = NULL,
    `type` = NULL,
    `username` = NULL,
    `caCerts` = NULL,
    initialize = function(`credential`, `internalUsername`, `password`, `publicKey`, `privateKey`, `server`, `type`, `username`, `caCerts`){
      if (!missing(`credential`)) {
        stopifnot(is.character(`credential`), length(`credential`) == 1)
        self$`credential` <- `credential`
      }
      if (!missing(`internalUsername`)) {
        stopifnot(is.character(`internalUsername`), length(`internalUsername`) == 1)
        self$`internalUsername` <- `internalUsername`
      }
      if (!missing(`password`)) {
        stopifnot(is.character(`password`), length(`password`) == 1)
        self$`password` <- `password`
      }
      if (!missing(`publicKey`)) {
        stopifnot(is.character(`publicKey`), length(`publicKey`) == 1)
        self$`publicKey` <- `publicKey`
      }
      if (!missing(`privateKey`)) {
        stopifnot(is.character(`privateKey`), length(`privateKey`) == 1)
        self$`privateKey` <- `privateKey`
      }
      if (!missing(`server`)) {
        stopifnot(R6::is.R6(`server`))
        self$`server` <- `server`
      }
      if (!missing(`type`)) {
        stopifnot(R6::is.R6(`type`))
        self$`type` <- `type`
      }
      if (!missing(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
      if (!missing(`caCerts`)) {
        stopifnot(is.character(`caCerts`), length(`caCerts`) == 1)
        self$`caCerts` <- `caCerts`
      }
    },
    toJSON = function() {
      SystemAuthConfigObject <- list()
      if (!is.null(self$`credential`)) {
        SystemAuthConfigObject[['credential']] <- self$`credential`
      }
      if (!is.null(self$`internalUsername`)) {
        SystemAuthConfigObject[['internalUsername']] <- self$`internalUsername`
      }
      if (!is.null(self$`password`)) {
        SystemAuthConfigObject[['password']] <- self$`password`
      }
      if (!is.null(self$`publicKey`)) {
        SystemAuthConfigObject[['publicKey']] <- self$`publicKey`
      }
      if (!is.null(self$`privateKey`)) {
        SystemAuthConfigObject[['privateKey']] <- self$`privateKey`
      }
      if (!is.null(self$`server`)) {
        SystemAuthConfigObject[['server']] <- self$`server`$toJSON()
      }
      if (!is.null(self$`type`)) {
        SystemAuthConfigObject[['type']] <- self$`type`$toJSON()
      }
      if (!is.null(self$`username`)) {
        SystemAuthConfigObject[['username']] <- self$`username`
      }
      if (!is.null(self$`caCerts`)) {
        SystemAuthConfigObject[['caCerts']] <- self$`caCerts`
      }

      SystemAuthConfigObject
    },
    fromJSON = function(SystemAuthConfigObject) {
      if (!is.null(SystemAuthConfigObject$`credential`)) {
        self$`credential` <- SystemAuthConfigObject$`credential`
      }
      if (!is.null(SystemAuthConfigObject$`internalUsername`)) {
        self$`internalUsername` <- SystemAuthConfigObject$`internalUsername`
      }
      if (!is.null(SystemAuthConfigObject$`password`)) {
        self$`password` <- SystemAuthConfigObject$`password`
      }
      if (!is.null(SystemAuthConfigObject$`publicKey`)) {
        self$`publicKey` <- SystemAuthConfigObject$`publicKey`
      }
      if (!is.null(SystemAuthConfigObject$`privateKey`)) {
        self$`privateKey` <- SystemAuthConfigObject$`privateKey`
      }
      if (!is.null(SystemAuthConfigObject$`server`)) {
        serverObject <- SystemAuthConfigServer$new()
        serverObject$fromJSON(jsonlite::toJSON(SystemAuthConfigObject$server, auto_unbox = TRUE))
        self$`server` <- serverObject
      }
      if (!is.null(SystemAuthConfigObject$`type`)) {
        typeObject <- SystemLoginAuthenticationType$new()
        typeObject$fromJSON(jsonlite::toJSON(SystemAuthConfigObject$type, auto_unbox = TRUE))
        self$`type` <- typeObject
      }
      if (!is.null(SystemAuthConfigObject$`username`)) {
        self$`username` <- SystemAuthConfigObject$`username`
      }
      if (!is.null(SystemAuthConfigObject$`caCerts`)) {
        self$`caCerts` <- SystemAuthConfigObject$`caCerts`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "credential": %s,
           "internalUsername": %s,
           "password": %s,
           "publicKey": %s,
           "privateKey": %s,
           "server": %s,
           "type": %s,
           "username": %s,
           "caCerts": %s
        }',
        self$`credential`,
        self$`internalUsername`,
        self$`password`,
        self$`publicKey`,
        self$`privateKey`,
        self$`server`$toJSON(),
        self$`type`$toJSON(),
        self$`username`,
        self$`caCerts`
      )
    },
    fromJSONString = function(SystemAuthConfigJson) {
      SystemAuthConfigObject <- jsonlite::fromJSON(SystemAuthConfigJson)
      self$`credential` <- SystemAuthConfigObject$`credential`
      self$`internalUsername` <- SystemAuthConfigObject$`internalUsername`
      self$`password` <- SystemAuthConfigObject$`password`
      self$`publicKey` <- SystemAuthConfigObject$`publicKey`
      self$`privateKey` <- SystemAuthConfigObject$`privateKey`
      SystemAuthConfigServerObject <- SystemAuthConfigServer$new()
      self$`server` <- SystemAuthConfigServerObject$fromJSON(jsonlite::toJSON(SystemAuthConfigObject$server, auto_unbox = TRUE))
      SystemLoginAuthenticationTypeObject <- SystemLoginAuthenticationType$new()
      self$`type` <- SystemLoginAuthenticationTypeObject$fromJSON(jsonlite::toJSON(SystemAuthConfigObject$type, auto_unbox = TRUE))
      self$`username` <- SystemAuthConfigObject$`username`
      self$`caCerts` <- SystemAuthConfigObject$`caCerts`
    }
  )
)
