# Agave Platform Science API
# 
# Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
# 
# OpenAPI spec version: 2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Transform Class
#'
#' @field decoders 
#' @field description 
#' @field descriptionurl 
#' @field enabled 
#' @field encoder 
#' @field name 
#' @field tags 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Transform <- R6::R6Class(
  'Transform',
  public = list(
    `decoders` = NULL,
    `description` = NULL,
    `descriptionurl` = NULL,
    `enabled` = NULL,
    `encoder` = NULL,
    `name` = NULL,
    `tags` = NULL,
    initialize = function(`decoders`, `description`, `descriptionurl`, `enabled`, `encoder`, `name`, `tags`){
      if (!missing(`decoders`)) {
        stopifnot(is.list(`decoders`), length(`decoders`) != 0)
        lapply(`decoders`, function(x) stopifnot(R6::is.R6(x)))
        self$`decoders` <- `decoders`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`descriptionurl`)) {
        stopifnot(is.character(`descriptionurl`), length(`descriptionurl`) == 1)
        self$`descriptionurl` <- `descriptionurl`
      }
      if (!missing(`enabled`)) {
        self$`enabled` <- `enabled`
      }
      if (!missing(`encoder`)) {
        stopifnot(R6::is.R6(`encoder`))
        self$`encoder` <- `encoder`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`tags`)) {
        stopifnot(is.list(`tags`), length(`tags`) != 0)
        lapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
    },
    toJSON = function() {
      TransformObject <- list()
      if (!is.null(self$`decoders`)) {
        TransformObject[['decoders']] <- lapply(self$`decoders`, function(x) x$toJSON())
      }
      if (!is.null(self$`description`)) {
        TransformObject[['description']] <- self$`description`
      }
      if (!is.null(self$`descriptionurl`)) {
        TransformObject[['descriptionurl']] <- self$`descriptionurl`
      }
      if (!is.null(self$`enabled`)) {
        TransformObject[['enabled']] <- self$`enabled`
      }
      if (!is.null(self$`encoder`)) {
        TransformObject[['encoder']] <- self$`encoder`$toJSON()
      }
      if (!is.null(self$`name`)) {
        TransformObject[['name']] <- self$`name`
      }
      if (!is.null(self$`tags`)) {
        TransformObject[['tags']] <- self$`tags`
      }

      TransformObject
    },
    fromJSON = function(TransformObject) {
      if (!is.null(TransformObject$`decoders`)) {
        self$`decoders` <- lapply(TransformObject$`decoders`, function(x) {
          decodersObject <- TransformDecoder$new()
          decodersObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          decodersObject
        })
      }
      if (!is.null(TransformObject$`description`)) {
        self$`description` <- TransformObject$`description`
      }
      if (!is.null(TransformObject$`descriptionurl`)) {
        self$`descriptionurl` <- TransformObject$`descriptionurl`
      }
      if (!is.null(TransformObject$`enabled`)) {
        self$`enabled` <- TransformObject$`enabled`
      }
      if (!is.null(TransformObject$`encoder`)) {
        encoderObject <- TransformEncoder$new()
        encoderObject$fromJSON(jsonlite::toJSON(TransformObject$encoder, auto_unbox = TRUE))
        self$`encoder` <- encoderObject
      }
      if (!is.null(TransformObject$`name`)) {
        self$`name` <- TransformObject$`name`
      }
      if (!is.null(TransformObject$`tags`)) {
        self$`tags` <- TransformObject$`tags`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "decoders": [%s],
           "description": %s,
           "descriptionurl": %s,
           "enabled": %s,
           "encoder": %s,
           "name": %s,
           "tags": [%s]
        }',
        lapply(self$`decoders`, function(x) paste(x$toJSON(), sep=",")),
        self$`description`,
        self$`descriptionurl`,
        self$`enabled`,
        self$`encoder`$toJSON(),
        self$`name`,
        lapply(self$`tags`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(TransformJson) {
      TransformObject <- jsonlite::fromJSON(TransformJson)
      self$`decoders` <- lapply(TransformObject$`decoders`, function(x) TransformDecoder$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`description` <- TransformObject$`description`
      self$`descriptionurl` <- TransformObject$`descriptionurl`
      self$`enabled` <- TransformObject$`enabled`
      TransformEncoderObject <- TransformEncoder$new()
      self$`encoder` <- TransformEncoderObject$fromJSON(jsonlite::toJSON(TransformObject$encoder, auto_unbox = TRUE))
      self$`name` <- TransformObject$`name`
      self$`tags` <- TransformObject$`tags`
    }
  )
)
